Implement markdown support for proposal templates and proposal view
decentdao/fractal-interface pull request #1432
Opened 2024-03-11 22:52 UTC by mudrila

Closes #1399 

## Changes:
- Changes to `ProposalTemplates` to display markdown from description. See `/daos/[daoAddress]/proposal-templates/new` page
- Rendering proposals in the list with stripped markdown styling. See `/daos/[daoAddress]/proposals`(Proposals list page) and `/daos/[daoAddress]` (DAO Dashboard - Activity list rendering affected)
- Rendering Markdown in proposal details. See `/daos/[daoAddress]/proposals/[proposalId]`

We certainly will need to revisit this once we adopt `ProposalTemplates` components. Probably we want to implement description preview / editor tab, so instead of visualizing description preview in the sidebar - we should be doing that via switching markdown input "mode" from edit to preview (or somehow displaying both of them).

I also tried to incorporate https://www.npmjs.com/package/@uiw/react-markdown-editor and https://github.com/OpusCapita/react-markdown - yet, I found them quite opinionated and thought it would be better to iterate over editor experience, so pure `TextArea` is the best option as of now, from my opinion

<img width="1593" alt="Знімок екрана 2024-03-11 о 23 36 47" src="https://github.com/decent-dao/fractal-interface/assets/25801162/fd32cc8c-9cbd-498c-8c76-97da989cfc89">
<img width="852" alt="Знімок екрана 2024-03-14 о 13 08 37" src="https://github.com/decent-dao/fractal-interface/assets/25801162/6818bd60-28a0-4d72-aeb7-27b3c53e0745">

## Testing:
1. Create Azorius or Multisig DAO
2. Create proposal with markdown in description. Make sure to put some very long strings to test edge cases
3. Make sure it properly appears in the proposals list, yet it should be truncated. In the list it should be as plain text without markdown styling applied, but also markdown symbols should be removed
4. Make sure markdown properly displayed on proposal details page

2024-03-12 03:27 UTC, adamgall reviewed
@mudrila, will you please
- Leave some comments here in Github on the various code changes of this PR.
- Describe in full where in the UI is affected by these changes.
- Explain the best way to test these changes.
Thanks!

2024-03-13 12:18 UTC, xraystyle1980 commented
I love the idea of supporting markdown and making the proposals more robust. I would like to spend some design time exploring how this change would effect the preview. Can we revisit this as design works through the proposal creation flow? I think making "Markdown support" a requirement of the prop creation flow redesign makes sense.

2024-03-14 19:22 UTC, adamgall requested changes
# Issue 1

On the Proposal Creation Description textarea, can you please enable resizing that textarea? Is there a reason that's been disabled?

<img width="854" alt="Screenshot 2024-03-14 at 2 54 57 PM" src="https://github.com/decent-dao/fractal-interface/assets/706929/193fc7e6-c067-4936-9687-812ce533be27">

---

# Issue 2

When displaying the Proposal Description after a proposal has been created, the description is showing up twice.

_Note: I did not add a title for this proposal. This seems to be the problem._

See the description that was created onchain:

https://sepolia.etherscan.io/tx/0x4a691de95190c84e852d858718ebe9229b6a7842d6ab6b1cad17005f3eafdb48

```
"description":"# This is my Proposal\n\n## This a sub heading\n\n_these are italics_"
```

This is what it looks like in the UI, both in Proposal List and Proposal Details:

<img width="1305" alt="Screenshot 2024-03-14 at 3 01 21 PM" src="https://github.com/decent-dao/fractal-interface/assets/706929/6584e00c-6893-455d-8a5a-22ebe2e0c462">

<img width="884" alt="Screenshot 2024-03-14 at 2 59 38 PM" src="https://github.com/decent-dao/fractal-interface/assets/706929/dfbcaf12-e962-4145-85d4-1e5f233ae7f6">

---

# Issue 3

When clicking on a Proposal Template (I do see the Markdown in the "Proposal Template Card", which is good!), the app crashes.

2024-03-15 19:57 UTC, Da-Colon reviewed
I have no additional code questions.

@xraystyle1980 @mudrila I guess we will look into adjust the preview in a future PR.

I'll do some additional testing once @adamgall questions/comments have been resolved.

2024-03-18 13:15 UTC, Da-Colon approved these changes
Looks good

We need to update the preview section to support the new Markdown Syntax. Not alot of space to show a good description. Proposal Template has a character limit of 300 I believe. But the proposal creation has more. I'm not sure why the limit on template?

![Image](https://github.com/orgs/decentdao/projects/32/assets/38386583/b3c54180-66a9-4e28-8b12-94feac470537)

Not too bad on the other end.

![Image](https://github.com/orgs/decentdao/projects/32/assets/38386583/bc6c195a-5e6c-4e57-9c36-bd5afc2fe91b)

(Unrelated) Did notice that when I click on 'show more' on the template it expanded on the main screen but also popped it up in the modal

Overall no glaring issues and works end-to-end

2024-03-18 14:57 UTC, adamgall requested changes
> On the Proposal Creation Description textarea, can you please enable resizing that textarea? Is there a reason that's been disabled?

This is still unresizable. Is that intentional?

2024-03-18 15:25 UTC, adamgall commented on src/components/ui/modals/ProposalTemplateModal.tsx
>        <Divider color="chocolate.700" />
Nitpick, but we'd probably want this `<Divider>` to render when _in_ the conditional with the `<Markdown>` component, right? Please test to make sure this looks correct, either way. We shouldn't have a divider rendering with nothing above it.

2024-03-18 15:27 UTC, adamgall commented on src/components/ui/proposal/Markdown.tsx
> +  }, [content]);
Why add this as a dependency to a `useEffect` that doesn't rely on it?

2024-03-18 15:29 UTC, adamgall commented on src/router.tsx
> +    ),
What was the reason for moving this out of `Providers` and into the `Router`?

2024-03-18 18:04 UTC, adamgall commented on src/components/Activity/ActivityDescriptionGovernance.tsx
> +      {metaData.title ? <Text>{metaData.title}</Text> : null}
Agree, this makes sense to me. Thank you!

2024-03-18 18:31 UTC, adamgall commented on src/components/ui/forms/InputComponent.tsx
> +        resize={resize as any}
Please no `any` if we can avoid it. This `resize` property should be one of four strings: `"vertical" | "horizontal" | "both" | "none"`

Defaulting to `vertical` is fine, because it seems like that's the behavior when this `resize` prop is left off of a `textarea` anyway.

2024-03-18 18:31 UTC, adamgall commented on src/router.tsx
> +    ),
Ok. I agree that placing `ModalProvider` inside of `Layout` doesn't seem right, but I also think it doesn't seem right inside of the `router` generator either. I just played around with this on my local machine, and sure enough it breaks unless that `ModalProvider` is inside of the `Router` object.  I understand why (we navigate from within a Modal). Can you please leave a comment in the code here explaining why this `Provider` isn't with the rest of them?

2024-03-18 20:15 UTC, adamgall approved these changes
SHIPIT

2024-03-18 20:15 UTC, merged