Replacing Rainbowkit with Web3Modal
decentdao/fractal-interface pull request #1465
Opened 2024-03-16 11:50 UTC by mudrila

This PR contains following changes:
- Replace `RainbowKit` with `Web3Modal`
- Add HTTPS support for local dev server in order to overcome possible issues for local development
- Implement trick to open web3 modal from 2nd attempt if 1st attempt fails (happens frequently both on local and deployed site)

Closes #1450 

Moving further, we'll have to update `web3Modal` version to `v4.x+` together with other web3 libraries (viem, wagmi, etc)

## Testing

1. Connect your wallet through different wallet providers (MetaMask, CoinBase, Injected Wallet, WalletConnect)
2. Try to create any type of Safe (better to test with Multisig and Azorius ERC-20/ERC-721). Make sure safe is properly created
3. Try to create proposal for that Safe(s). Make sure proposal properly created
4. Try to vote on that proposal. Make sure vote appears right after you voted, breakdown updated properly, etc.
5. Try to execute that proposal

2024-03-18 13:24 UTC, Da-Colon requested changes
Loading a DAO up (Azorius) Seems to be really slow. looking at the network tab, all the requests are going through walletconnect provider. 

![image](https://github.com/decentdao/fractal-interface/assets/38386583/5c6bb108-5ce8-46ef-a9a8-42b8986eaaf3)

Can also you talk a little bit on why you needed to add mkcert plugin and HTTPS support?

2024-03-18 13:24 UTC, Da-Colon commented on src/components/ui/menus/AccountDisplay/MenuItems.tsx
> +        open();
So prior to the NextJS removal update. I could not get `useWeb3Modal` to work properly within the header, while still calling createWeb3Modal else where in the app. The Header component seem to be getting mounted before the providers were getting set and that function is called. Since it seems to be 'working' now but flaky I wonder if there is something in how we mount our header components that still wonky

2024-03-18 13:24 UTC, Da-Colon commented on src/providers/NetworkConfig/testWallet.ts
> +export const testWallet = ({ chains }: MyWalletOptions): any => ({
You can probably just remove this completely

2024-03-18 19:47 UTC, adamgall requested changes

2024-03-18 19:47 UTC, adamgall commented on src/components/ui/utils/ConnectWalletToast.tsx
Doesn't look like this file is being imported anywhere. Safe to remove?

2024-03-18 19:47 UTC, adamgall commented on src/providers/NetworkConfig/web3-modal.config.ts
> +  url: 'https://fractalframework.xyz',
I believe this should include the full subdomain. See the code and"Important" box here: https://docs.walletconnect.com/web3modal/react/about

2024-03-18 19:47 UTC, adamgall commented on src/providers/NetworkConfig/web3-modal.config.ts
> +  url: 'https://fractalframework.xyz',
Please pull (copy) all of these out of our index.html. Use env vars where you can.

2024-03-18 19:47 UTC, adamgall commented on src/providers/NetworkConfig/web3-modal.config.ts
> +  enableWalletConnect: true,
These are all true by default, no need to specify them.

2024-03-18 19:47 UTC, adamgall commented on vite.config.mts
I don't like this, seems like the wrong thing to solve for. I removed these changes from my local branch and had no issues with the rest of the code in this branch (which was a nice clean easy implementation!).

@mudrila what problems are you having locally that pushed you to include this code? I'd like to remove this code and help you fix the actual problem you're encountering locally.

2024-03-18 20:44 UTC, adamgall requested changes

2024-03-18 20:44 UTC, adamgall commented on src/providers/NetworkConfig/web3-modal.config.ts
The `publicClient` which comes out of `configureChains` is exported, but not being consumed anywhere. Can probably remove that.

2024-03-20 17:40 UTC, adamgall commented on src/hooks/utils/useDisplayName.ts
> +  const { chainId } = useNetworkConfig();
Why not pull the `chain` object out of `wagmi`'s `useAccount()`? Can either one of `useNetworkConfig()` or `useAccount()` be used to get the current network?

2024-03-20 17:58 UTC, adamgall reviewed
Just a couple of comments, but lookin good!

2024-03-20 17:58 UTC, adamgall commented on src/hooks/utils/useDisplayName.ts
> +  const { chainId } = useNetworkConfig();
Why not pull the `chain` object out of `wagmi`'s `useAccount()`? Can either one of `useNetworkConfig()` or `useAccount()` be used to get the current network?

2024-03-20 17:58 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> +  });
Is the `subgraphChainName` different than `chain.name` that comes out of `wagmi`'s `useAccount()`?

2024-03-21 11:51 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> +  });
Got it, thanks. I like how the `subgraphChainName` is stored in NetworkConfig.

2024-03-21 12:31 UTC, adamgall approved these changes
shipit

edit: not yet

2024-03-21 12:36 UTC, tomstuart123 commented
**1) Coinbase Wallet + Brave  **
Azorious
- Try to create Azorious Safe = SUCCESS
- Delegate vote = SUCCESS
- Try to create proposal for that Safe(s). = SUCCESS
- Try to vote on that proposal. Make sure vote appears right after you voted, breakdown updated properly, etc. = SUCCESS
- Try to execute that proposal = SUCCESS

_Multisig_
- Try to create Azorious Safe = SUCCESS
- Try to create proposal for that Safe(s). = SUCCESS
- Try to vote on that proposal. Make sure vote appears right after you voted, breakdown updated properly, etc. = SUCCESS
- Try to execute that proposal = SUCCESS

**2) SafeUI +WC + Chrome  **
_Azorious_
- create azoriuos safe - SUCCESS - no issue
- Delegate vote = PARTIAL SUCCESS - issue - delegate vote toaster didn't remove by itself
- Try to create proposal for that Safe(s). = PARTIAL SUCCESS - issue - 'creating proposal' toaster didn't remove- Try to vote on that proposal. = PARTIAL SUCCESS - issue - 'casting vote' toaster didn't remove by itself
- Try to execute that proposal = PARTIAL SUCCESS - issue - 'casting vote' toaster didn't remove by itself

_Multisig_
- create a safe - PARTIAL SUCCESS - initally safe app said 'failed - untrusted transaction' then weirdly it went through got this link - https://app.safe.global/transactions/tx?id=multisig_0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5_0x845eeb01cff0891edb9cbc306bfc6f6cb64c513033cd02c8b1f83ebcba96f1de&safe=sep:0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5
- create a proposal - failed twice - for changing name and adding a signer - https://app.safe.global/transactions/messages?safe=sep:0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5

<img width="465" alt="Screenshot 2024-03-21 at 12 09 44" src="https://github.com/decentdao/fractal-interface/assets/31554133/48be0c47-0db0-45ed-8faa-1a576f2d477e">

here's the safe with the issues - https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0xa719FcC542a59A6C52b4C482e562334bF1aF9828

- sign transaction - it said success in fractal and safe app but no signature actually made to pass transatciont. https://app.safe.global/transactions/messages?safe=sep%3A0xA3F3D0e6C7471e156D146dde09D336aE2a6091C5 ? https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x652A8159eCc60F63589FbE35FBDa0E77679BA70E/proposals/0x0f6d35d0da46b120f26aee9d853d198a21ae1d28ae7763dc26c10caf409f1119


**3) Metamask + Chrome  **
_Azorious_
- Try to create Azorious Safe =SUCCESS
- Delegate vote (azorius) = SUCCESS
- Try to create proposal for that Safe(s). = SUCCESSS
- Try to vote on that proposal. Make sure vote appears right after you voted, breakdown updated properly, etc  = SUCCESS
- Try to execute that proposal = SUCCESS

Multisig
- Try to create Azorious Safe = SUCCESS
- Try to create proposal for that Safe(s). = SUCCESS
- Try to vote on that proposal. Make sure vote appears right after you voted, breakdown updated properly, etc. = SUCCESS
- Try to execute that proposal = SUCCESS

Note links to test safes
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0xa719FcC542a59A6C52b4C482e562334bF1aF9828
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x7DA5B360cf079b8c9A78F954cc7F01f94c21DA97
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x5D1b267727eb4b84b5Ee9A1b481Ae0A0293C5e78
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x652A8159eCc60F63589FbE35FBDa0E77679BA70E
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x21d14603f1c55a5be95d49A47CF44707090332de
--? https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x652A8159eCc60F63589FbE35FBDa0E77679BA70E
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x5De7c6164710DF979E73a7463E068f34589864dA
--> https://deploy-preview-1465.app.dev.fractalframework.xyz/daos/0x7DA5B360cf079b8c9A78F954cc7F01f94c21DA97

2024-03-21 13:05 UTC, adamgall requested changes
Ah, found another thing that should be fixed up as part of the different behaviors of RainbowKit and Web3Modal.

2024-03-21 13:05 UTC, adamgall commented on src/pages/DAOController.tsx
Some of the control flow in this file could be cleaned up as part of this PR.

Notably, with web3modal, the `InvalidChain` component doesn't seem to be relevant any longer.

1. Connecting with your wallet.
2. Use your wallet's UI to switch to an unsupported chain.
3. See how web3modal pops up immediately (instead of `<InvalidChain />` being rendered), informing the user of their options.

2024-03-21 13:15 UTC, adamgall commented on src/pages/DAOController.tsx
Maybe the fix is this? Seems like we can greatly simplify that big conditional block

```ts
  const validSafe = node.safe;
  let display;

  if (import.meta.env.VITE_APP_TESTING_ENVIRONMENT) {
    display = (
      <ChakraProvider theme={activeTheme}>
        <Outlet />
      </ChakraProvider>
    );
  } else if (nodeLoading || validSafe || !errorLoading) {
    display = <Outlet />;
  } else {
    display = <InvalidSafe />;
  }
```

Then of course delete the `InvalidChain` components and any now-unused translations.

2024-03-21 13:21 UTC, adamgall commented on src/pages/DAOController.tsx
Also, just noticing, the return statement at the bottom of this file doesn't seem to be doing much. We can't set `<title>` here, it has no effect on anything. Might as well just get rid of that an only `return display;`

2024-03-21 15:40 UTC, tomstuart123 approved these changes

2024-03-21 17:02 UTC, adamgall approved these changes

2024-03-21 17:08 UTC, merged