Upgrade wagmi, viem, web3modal
decentdao/fractal-interface pull request #1467
Opened 2024-03-18 21:38 UTC by mudrila

This PR migrates from `wagmi` v1 to `wagmi` v2 and upgrades related packages version, including following:

- `viem` (upgraded to `v2`)
- `@web3modal/wagmi` (upgraded to `v4`)
- `@tanstack/react-query` (added since it is `peerDependency` of `wagmi`)
- `Node.js` (upgraded to current LTS, `20.11.1`)
- `@walletconnect/ethereum-provider` (removed)

This PR does not include removing `ethers` nor upgrading that - comes in scope of further implementation.
Also solves https://github.com/decentdao/fractal-interface/pull/1465#pullrequestreview-1942944244

2024-03-19 15:27 UTC, adamgall requested changes

2024-03-19 15:27 UTC, adamgall commented on src/components/ui/menus/AccountDisplay/MenuItemNetwork.tsx
> +            switchChain({ chainId: Number(e.target.value) });
Switching to Polygon causes the app to crash.

2024-03-19 23:55 UTC, adamgall commented
@mudrila in these commits, there are an awful lot of changes to the `package-lock.json` file. This makes sense due to various packages being upgraded. However I'm curious: were there any other reasons for the changes to this lockfile? Things including, but not limited to:
- running `npm update`
- deleting the `package-lock.json` file and letting it regenerate via `npm install`
- anything else?

2024-03-20 00:14 UTC, adamgall commented on src/hooks/utils/useUpdateTimer.tsx
> +  const timers = useRef<Map<string, NodeJS.Timeout>>(new Map());
As far as I can tell, the project builds and runs fine when this is kept as `NodeJS.Timer`

2024-03-20 00:14 UTC, adamgall commented on src/hooks/utils/useMasterCopy.ts
> +        return [masterCopyAddress, null];
As far as I can tell, the project builds and runs just fine without these changes.

2024-03-20 00:14 UTC, adamgall commented on src/hooks/utils/useAvatar.ts
> +    name: account as Address,
This `account` should be typed as an `Address` in the hook's input parameters, and that change is propogated back through all uses of this hook in the app.

2024-03-20 00:14 UTC, adamgall commented on src/components/ui/proposal/useProposalCountdown.tsx
> +  let updateStateInterval = useRef<NodeJS.Timeout | undefined>();
As far as I can tell, the project builds and runs just fine without these changes.

2024-03-20 00:14 UTC, adamgall commented on src/components/ui/proposal/useProposalCountdown.tsx
> +    let countdownInterval: NodeJS.Timeout | undefined;
As far as I can tell, the project builds and runs just fine without these changes.

2024-03-20 00:14 UTC, adamgall commented on src/components/ui/proposal/useProposalCountdown.tsx
> +      }
As far as I can tell, the project builds and runs just fine without these changes. `clearInterval` accepts `undefined` so this should be fine without the conditional check.

2024-03-20 00:14 UTC, adamgall commented on src/components/ui/forms/BigNumberInput.tsx
> +  placeholder?: string;
Why was this added?

2024-03-20 00:14 UTC, adamgall commented on src/components/ui/forms/ABISelector.tsx
> +      if (client && target && ((ensAddress && isAddress(ensAddress)) || isAddress(target))) {
Why was `client` added to this list?

2024-03-20 00:15 UTC, adamgall reviewed
A handful of comments. In addition to the line-by-line comments, a big other question I have is:

In these commits, there are an awful lot of changes to the `package-lock.json` file. This makes sense due to various packages being upgraded. However I'm curious: were there any other reasons for the changes to this lockfile? Things including, but not limited to:
- running `npm update`
- deleting the `package-lock.json` file and letting it regenerate via `npm install`
- anything else?

2024-03-20 12:08 UTC, adamgall commented on tsconfig.json
> +  "include": ["src", "tests", "test", "app", "vite.config.mts"]
I'm able to build with "netlify/functions" in the "include" section here. Are you not?

2024-03-20 12:08 UTC, adamgall commented on src/providers/Ethers/index.tsx
>    const provider = useMemo(() => {
Ah yes, I see now! Thanks.

2024-03-20 12:08 UTC, adamgall commented on src/hooks/utils/useAvatar.ts
> +    name: account as Address,
Got it, thanks.

2024-03-20 14:18 UTC, adamgall commented
> > @mudrila A handful of comments. In addition to the line-by-line comments, a big other question I have is:
> > In these commits, there are an awful lot of changes to the package-lock.json file. This makes sense due to various packages being upgraded. However I'm curious: were there any other reasons for the changes to this lockfile? Things including, but not limited to:
> 
> * running `npm update`
> * deleting the `package-lock.json` file and letting it regenerate via `npm install`
> * anything else?
> 
> So those massive changes were caused by me deleting the `package-lock.json` and re-generating that. That was the reason we were getting newest `TypeScript` version and build failures caused by that. That's also was leading to CI build to fail. When I realized this - I copied over `package-lock.json` from `develop`, executed `npm install` to get updates from newest versions of packages (`wagmi`, `viem`, `web3modal` etc.) and pushed updated lock file. That solved the problem with these redundant changes and CI build failure.
> 
> TBH I wasn't expecting anything "bad" from deleting `package-lock.json` - I remember that was the case for `CRA` but with `Next.js` that wasn't happening and my idea was that with `Vite` there won't be any problems - but yeah, it broke the build, lessons learned 😄

Ok, makes sense. In general, it's a bad idea to delete `package-lock.json` and regenerate it from scratch. That will likely cause lots of changes to package versions that are unintended, and can wreak havoc on a large codebase with many dependencies due to so many packages changing at once.

Glad to hear that was reverted.

**So @mudrila to be clear, the only changes to `package-lock.json` are the result of explicitly updating the packages we wanted to update, right?**

2024-03-20 14:29 UTC, adamgall requested changes

2024-03-20 14:29 UTC, adamgall commented on package-lock.json
While we're here, might as well remove the `version` property from this file, and update it to `lockfileVersion: 3` (can be done by running `npm install --lockfile-version 3`).

2024-03-20 15:40 UTC, Da-Colon approved these changes

2024-03-20 15:46 UTC, merged