Update Proposal list
decentdao/fractal-interface pull request #1472
Opened 2024-03-20 04:19 UTC by Da-Colon

Updated Proposal List (Dashboard, Proposals (Governance page), and updates Badge on Details

# Screenshots:

## Token DAO
![localhost_3000_daos_0x259a5770d7242b5aBa7420926690E90c69037d10 (1)](https://github.com/decentdao/fractal-interface/assets/38386583/c68b12bb-4b69-466a-a35b-1473944c17ef)
## Multisig DAO
![localhost_3000_daos_0x70484d88cB248b9a5150d133fEDBa7948AfC9b0B(Desktop)](https://github.com/decentdao/fractal-interface/assets/38386583/3fac6012-e4fb-4112-86a1-789a60e47340)
## Snapshot Proposals
- Note here. Proposal Description format is handled by the Markdown. I removed a conditional that was doing plaintext when truncated to let the markdown do its thing. Its more or less controlled by number of lines now.
![localhost_3000_daos_0x70484d88cB248b9a5150d133fEDBa7948AfC9b0B_proposals_2 (1)](https://github.com/decentdao/fractal-interface/assets/38386583/1ca3a2b7-99d0-4c3a-9977-99a6f239589a)
## Responsive Design
![localhost_3000_daos_0x70484d88cB248b9a5150d133fEDBa7948AfC9b0B](https://github.com/decentdao/fractal-interface/assets/38386583/01f2d8e8-7d7e-41fb-b467-a06202a6f4a1)
## Details Page update (Badge | Proposal Title | Proposal Description)
![localhost_3000_daos_0x70484d88cB248b9a5150d133fEDBa7948AfC9b0B_proposals_2](https://github.com/decentdao/fractal-interface/assets/38386583/5126bb71-61ae-460c-8beb-5d124ace6cc0)

Closes #1448

2024-03-20 04:31 UTC, Da-Colon commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
Main entry to changes. Replaces current `ActivityGovernance` component.

2024-03-20 04:31 UTC, Da-Colon commented on src/components/ui/badges/Badge.tsx
> +const lightBlueText = '#D1DCF5'
New colors are hardcoded in file for now. Not ideal I tried to use the name given in the figma file but some don't have colors yet. This can be move to design system once overhaul is done.

2024-03-20 04:31 UTC, Da-Colon commented on src/components/ui/badges/QuorumBadge.tsx
uses `meetsQuorum` to pull the information directly from contract for linearERC20 strategy token DAOs. I created a issue for update ERC721 contract to do the same.

2024-03-20 04:31 UTC, Da-Colon commented on src/components/ui/proposal/Markdown.tsx
> -  }
I don't think we need this. Markdown looks pretty good. going straight to the markdown below. Let me know @mudrila if this is a bad idea.

2024-03-20 04:31 UTC, Da-Colon commented on src/i18n/locales/uk/common.json
Are we still removing translations if the english json is updated?

2024-03-20 05:02 UTC, Da-Colon commented
![localhost_3000_daos_0xDD73b64C8845868CCddB30df83929fBA63b4d284](https://github.com/decentdao/fractal-interface/assets/38386583/90a30961-710f-4b6a-8e91-0a58679c1793)

Here is the current UI when Frozen.

2024-03-20 16:56 UTC, nicolaus-sherrill requested changes
So far, I'm only able to find `Executed`, `Rejected`,and `Closed` in my testing but I'm seeing issues with color and vertical alignment on them.

See images below:
<img width="901" alt="Screenshot 2024-03-20 at 11 49 51 AM" src="https://github.com/decentdao/fractal-interface/assets/62394931/e7f6cb5c-d91e-4994-9037-07e5e3f174cf">
<img width="738" alt="Screenshot 2024-03-20 at 11 55 09 AM" src="https://github.com/decentdao/fractal-interface/assets/62394931/bfcacb67-53ab-4190-8ed9-f608d6faa9d7">
<img width="711" alt="Screenshot 2024-03-20 at 11 55 14 AM" src="https://github.com/decentdao/fractal-interface/assets/62394931/e9ab9973-8fa0-4eeb-869a-beb108597878">

2024-03-21 14:01 UTC, Da-Colon commented on src/components/ui/badges/QuorumBadge.tsx
> +    return null;
https://github.com/decentdao/fractal-interface/issues/1477

2024-03-21 14:05 UTC, Da-Colon commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +        _hover={{ bg: '#0B0A09' }}
There wasn't a name in the design system for these values yet. So we would be searching for these by hex values later anyway

2024-03-22 16:49 UTC, xraystyle1980 commented
The spacing is off. All status badges should have 8px padding, 8px gap between icon and label, and 4px border radius. (the colors are not 100% but we have new colors coming soon so I'm not pushing back on that)

![image](https://github.com/decentdao/fractal-interface/assets/18615633/abb9af09-b3d2-418b-a147-532c0f1553cc)

2024-03-22 17:19 UTC, Da-Colon commented
@xraystyle1980 Colors are wrong? I'll take a look? I'll take another look at the padding as well.

2024-03-25 13:40 UTC, Da-Colon commented
@xraystyle1980 Ah I see ha. There were a few updates to the colors I didn't notice and didn't realize there was a hover text color. Ive updated the badge. I've adjusted the padding around the badge to 8px to match the designs more closely.

2024-03-25 18:07 UTC, nicolaus-sherrill commented
> @Da-Colon
> 
> Two line proposal title's force the proposer address to the wrong line
> 
> see below proposal 14 (i.e. address below title) v.s proposal 13 where the address is on the same line
> 
> ![Screenshot 2024-03-25 at 15 46 36](https://private-user-images.githubusercontent.com/31554133/316564809-48919f35-a288-4805-8659-dafd9d4e3a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTAyMjAsIm5iZiI6MTcxMTM4OTkyMCwicGF0aCI6Ii8zMTU1NDEzMy8zMTY1NjQ4MDktNDg5MTlmMzUtYTI4OC00ODA1LTg2NTktZGFmZDlkNGUzYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODYzMWFkMWJhOTM1MTY4MDA3ZGM4NWUxYjc3ODRmNTQ1NWZhMzA2N2RiN2UxMzk5OWJmYzA4MWE1YmJhZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RD7EUhq6eZmz9-F2rRqQ-oz-akcDvKtnyFOerFvJjE)

My take is that keeping proposal titles to one line, and implementing some visual way to represent that there is more of the title would be best.

However, if that's not reasonable/feasible, definitely want to see that author name on the same line as the proposal title.

2024-03-25 18:17 UTC, adamgall requested changes

2024-03-25 18:17 UTC, adamgall commented on src/components/ui/proposal/Markdown.tsx
> -import removeMd from 'remove-markdown';
If we _are_ getting rid of this, then please remove it from `package.json` too

2024-03-25 18:17 UTC, adamgall commented on src/components/ui/badges/QuorumBadge.tsx
> +    );
This seems less important to implement, now that I see that it _still_ requires an input of `yes` and `abstain` votes.

The original idea with calling the contract was to allow for DAOs to subclass their own contracts and implement quorum in different ways, and for this code to allow for that. But there's still a requirement here that `meetsQuorum` takes in `yes` and `abstain` vote counts. If a DAO wanted to include `no` votes, there's no way that this function could account for that.

I think this should be undone in this PR, so we don't need to make this extra contract call. Can we still just calculate it on the frontend?

2024-03-25 18:17 UTC, adamgall commented on src/components/ui/badges/Badge.tsx
> +  // add as undefined to avoid breaking changes
Don't think this comment is necessary in the codebase, would be better as a PR comment

2024-03-25 18:52 UTC, Da-Colon commented on src/components/ui/badges/QuorumBadge.tsx
> +    );
Yeah I can reverse these changes for sure. for now

2024-03-25 18:52 UTC, Da-Colon commented on src/components/ui/badges/Badge.tsx
> +  // add as undefined to avoid breaking changes
Cool cool

2024-03-25 19:01 UTC, Da-Colon commented on src/components/ui/proposal/Markdown.tsx
> -import removeMd from 'remove-markdown';
Done.

2024-03-25 19:05 UTC, Da-Colon commented
> > @Da-Colon
> > Two line proposal title's force the proposer address to the wrong line
> > see below proposal 14 (i.e. address below title) v.s proposal 13 where the address is on the same line
> > ![Screenshot 2024-03-25 at 15 46 36](https://private-user-images.githubusercontent.com/31554133/316564809-48919f35-a288-4805-8659-dafd9d4e3a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTAyMjAsIm5iZiI6MTcxMTM4OTkyMCwicGF0aCI6Ii8zMTU1NDEzMy8zMTY1NjQ4MDktNDg5MTlmMzUtYTI4OC00ODA1LTg2NTktZGFmZDlkNGUzYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODYzMWFkMWJhOTM1MTY4MDA3ZGM4NWUxYjc3ODRmNTQ1NWZhMzA2N2RiN2UxMzk5OWJmYzA4MWE1YmJhZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RD7EUhq6eZmz9-F2rRqQ-oz-akcDvKtnyFOerFvJjE)
> 
> My take is that keeping proposal titles to one line, and implementing some visual way to represent that there is more of the title would be best.
> 
> However, if that's not reasonable/feasible, definitely want to see that author name on the same line as the proposal title.

Yeah I actually ran into quite a bit of an issue getting these to play together with longer titles. Almost all the Proposals are fine except for the longer ones. 

![localhost_3000_daos_0xD26c85D435F02DaB8B220cd4D2d398f6f646e235 (1)](https://github.com/decentdao/fractal-interface/assets/38386583/b73df32c-e777-4f38-8997-535dd58d7108)

![localhost_3000_daos_0xD26c85D435F02DaB8B220cd4D2d398f6f646e235 (3)](https://github.com/decentdao/fractal-interface/assets/38386583/2bf71ab5-375a-49a7-8aa5-6e9d5d835c0e)

2024-03-25 19:24 UTC, adamgall approved these changes

2024-03-26 15:32 UTC, nicolaus-sherrill approved these changes
Thanks for making those pixel-perfect tweaks. Looks great!

2024-03-26 15:34 UTC, merged