Enhancement/1483 chainspacing
decentdao/fractal-interface pull request #1496
Opened 2024-03-27 03:22 UTC by adamgall

Closes #1483 

_Currently a Draft. This PR will be open to review once #1494 is merged_

This PR implements `chainspacing` in the URL.

All URLs that exist in the context of a Safe have a network ID (same ones that the Safe UI uses) prefixed to the address.

Additionally, error page logic has been separated to clearly identify the two scenarios that might occur for a Safe being unable to be loaded:
- The given address simply isn't a Safe on the expected (as per the network prefix) Safe.
- The app is connected to a different network than what the Safe is expecting (as per the network prefix).

Additionally, stronger typing has been enforced in the many places were navigation links exist. This stronger typing required early-exiting rendering attempts where either the network prefix or address are not available yet (e.g. as a Safe is loading), so special review and testing should be taken to ensure that the logical changes around rendering links was implemented correctly.

2024-03-27 04:25 UTC, adamgall reviewed
Left a handful of comments on some implementation details. Would love more eyes and brains on this.

2024-03-27 04:25 UTC, adamgall commented on src/hooks/DAO/useDeployDAO.ts
> +  const { addressPrefix } = useNetworkConfig();
Unsure if this was the proper place to get the network prefix from. I don't think it's guaranteed that we'll have a loaded Safe when this hook is being used, so that's why I pulled the value from `useNetworkConfig`.

2024-03-27 04:25 UTC, adamgall commented on src/types/fractal.ts
> +  daoNetwork: string | null;
Here's a big question that might have some big consequences for this PR... was it even appropriate to add this new property to the `FractalNode` state? Should I just be pulling the network for a given DAO from `useNetworkConfig`? Are there places in the app where the DAO loaded up in state belongs to a _different network_ than the one that the app is connected to (which is known in `useNetworkConfig`)?

2024-03-27 04:25 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  }
Unsure if this is the appropriate way to throw these critical errors... Maybe these need to be caught in an Error Boundary somewhere. Thoughts? Can test these out by manually removing sections of the address (like the network prefix).

2024-03-27 04:25 UTC, adamgall commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +  const { chainId, safeBaseURL, addressPrefix } = useNetworkConfig();
Here's another place where I pulled the network prefix from `useNetworkConfig` instead of `useFractal`. Thoughts on which approach is more appropriate?

2024-03-27 04:25 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +    async (_daoNetwork: string, _daoAddress: string, _connectedNetwork: string) => {
This function now takes both the network for the given DAO, as well as the network we're currently connected to, in order to properly set the appropriate error state.

2024-03-27 04:25 UTC, adamgall commented on src/components/ui/modals/ConfirmModifyGovernanceModal.tsx
> +  }
Is this cool? I think and hope so.

2024-03-27 04:25 UTC, adamgall commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +        }
Is this new conditional cool? I think and hope so.

2024-03-27 04:25 UTC, adamgall commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +    }
Is this new conditional cool? I think and hope so.

2024-03-27 04:25 UTC, adamgall commented on src/components/ui/menus/FavoritesMenu/FavoritesList.tsx
> +                network={addressPrefix}
I don't love having to pull the "current network" off of `useNetworkConfig` to render these Favorite links. Wish I could have pulled these directly off the local storage information, but those are not very well reusable. So, since the `favoritesList` is only coming back with favorites for the given connected network anyway, this seemed safe enough for now.

2024-03-27 04:25 UTC, adamgall commented on src/components/ui/menus/DAOSearch/SearchDisplay.tsx
> +            }}
Not super related to this PR, but I snuck this change in here anyway. Basically, made it so that only the button in the search result list is clickable, not the whole element.

2024-03-27 04:25 UTC, adamgall commented on src/components/pages/DaoSettings/components/Metadata/index.tsx
> +    }
Is this new conditional cool? I think and hope so.

2024-03-27 04:25 UTC, adamgall commented on src/components/pages/DaoDashboard/Info/index.tsx
> +              )}
Is this new conditional cool? I think and hope so.

2024-03-27 04:25 UTC, adamgall commented on src/components/pages/DaoDashboard/Info/index.tsx
> +              )}
Is this new conditional cool? I think and hope so.

2024-03-27 04:25 UTC, adamgall commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  }
Is this cool? I think and hope so.

2024-03-27 13:14 UTC, tomstuart123 approved these changes

2024-03-27 13:15 UTC, tomstuart123 commented
@adamgall - approval given 

I did lots of testing of this PR with Decent, shutter, and myosin by pasting old URLs into this deploy link
Good news is they were all handled successfully :slightly_smiling_face:

I can also confirm your point above that linking to an old link to the treasury page, will now link back to the core homepage (note - this is absolutely fine)

2024-03-27 13:44 UTC, Da-Colon commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  }
Shouldn't by time this mounts. You can also just return `null`

2024-03-27 13:50 UTC, adamgall commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  }
`return null;`! of course. i was just doing `return;` originally and then the compiler was yelling at me (because the implicit `undefined` there wasn't acceptable where the component was being instantiated). I forgot about returning null. i like that better, will go update now.

2024-03-27 13:52 UTC, adamgall commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  }
updated and pushed

2024-03-28 03:29 UTC, Da-Colon requested changes
Nice! Answer to your big question and one requested change in `ManageDAOMenu`

2024-03-28 03:29 UTC, Da-Colon commented on src/components/ui/menus/FavoritesMenu/FavoritesList.tsx
> +                network={addressPrefix}
We've talked before about revisiting LocalStorage setup. Should a card be made to start noting this?

2024-03-28 03:29 UTC, Da-Colon commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> -  const safeAddress = fractalNode?.daoAddress;
The way the safeAddress is used in this component needs to be the same. `ManageDAOMenu` it used to pull subDAO data as well on Hierarchy Page. 

The props should be what is used not the address from global state.

2024-03-28 03:29 UTC, Da-Colon commented on src/constants/routes.ts
> +  relative: (daoNetwork: string, daoAddress: string, ...args: string[]) => string;
o I see em 👁️

2024-03-28 03:29 UTC, Da-Colon commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +  const { chainId, safeBaseURL, addressPrefix } = useNetworkConfig();
No thoughts, I don't see the harm in pulling from NetworkConfig provider

2024-03-28 03:29 UTC, Da-Colon commented on src/hooks/DAO/useDAOController.ts
> +  }
Haven't live tested. What happens? the ErrorBoundary? (I'll probably test it before you respond ha.)

2024-03-28 03:29 UTC, Da-Colon commented on src/main.tsx
> +        <FractalRouterProvider />
that makes sense

2024-03-28 03:29 UTC, Da-Colon commented on src/types/fractal.ts
> +  daoNetwork: string | null;
hmmm ah now I see the thought here (last comment I've read ha). 

Need to think more on this. At first I was going to say it doesn't matter but we probably don't need this in two places. as these should always be the same. The DAO won't work if the contracts are the right state. these things are tied together. So makes sense to keep this only read from a single place (IMO networkConfig)

2024-03-28 19:45 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  }
I need to test this too

2024-03-28 19:50 UTC, adamgall commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> -  const safeAddress = fractalNode?.daoAddress;
Oh snap, great find. I didn't realize I was making an actual change Here. I didn't realize that `fractalNode` came from the constructor, I was incorrectly thinking it came out of `useFractal()` a few lines above.

2024-03-28 23:18 UTC, adamgall reviewed
Left a couple new comments as per my most recent pushed work.

In general, the majority of my _new_ updates tackle:
1. Fixing the unintentional bug I introduced in `ManageDAOMenu` (thanks @Da-Colon for finding that)
2. removing `daoNetwork` from Fractal state, and just using the value from `useNetworkConfig` instead, throughout the app.

2024-03-28 23:18 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +        setWrongNetwork(true);
If the address prefix (from the URL) is different than the address prefix (of the network the app is connected to) reset the DAO and set this specific error state

2024-03-28 23:18 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +      addressPrefix !== connectedAddressPrefix
Two thing here:
1. Cleaned up the existing conditional -- "dao address" is always a non-empty string, so we don't need to check for its existence like we were doing originally.
2. added an "or" condition to check if the connected address prefix has changed from what's in the url

2024-03-28 23:18 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  }
Just tested it, this does not exist in an Error Boundary

![Screenshot 2024-03-28 at 7 15 27 PM](https://github.com/decentdao/fractal-interface/assets/706929/5ffbfbb4-3ee4-4a5b-ad90-a5f8a786af9c)

I'll need to fix this as part of this PR.

2024-03-29 03:33 UTC, adamgall commented on src/pages/DAOController.tsx
> +  const { errorLoading, wrongNetwork, invalidQuery } = useDAOController();
`useDAOController` will simply return back to us information for if any of the three error states have hit.

2024-03-29 03:33 UTC, adamgall commented on src/pages/DAOController.tsx
> +    display = <Outlet />;
If any of the three error states have hit, show the appropriate LoadingProblem, otherwise let that mfkr load

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  const skip = invalidQuery || wrongNetwork;
Just setting up some state here, to be used down below. This is where we check to see if the query param is formatted correctly, and that we're on the right network. Then we have a variable called `skip` which is needed to be passed into `useFractalNode`, which will, you guessed it, skip loading and reset state if true.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +
Here we are, let `useFractalNode` do it's thing. The only return value from here is `errorLoading` which signifies the error state that means that the given address just isn't a Safe.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  return { invalidQuery, wrongNetwork, errorLoading };
Return `invalidQuery`, `wrongNetwork` (both of which were determined in this hook), and `errorLoading` (which will have come from the returned value of `useFractalNode`).

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +  );
Made a new little helper function to do this because it was repeated a few times.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> -  }, [safeAPI, daoAddress]);
Ended up just inlining this, it was a one-liner.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> -  const [nodeLoading, setNodeLoading] = useState<boolean>(true);
We don't actually care about tracking whether or not the DAO is loading. 

Reason: From the point of view of the rest of the app, as long as there are no errors, we try to render. If there's no data in state, loading components are shown. As data finds its way into state, the components render that data.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
>      },
This was mostly just flattening out the logic, putting all errors and exiting up top, and doing the happy path stuff at the bottom.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +      return;
Ok, into the main loop useEffect for this hook. If the passed-in `skip` is true (which means there was an error with the query param or we're on the wrong network), then clear state and GTFO.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +    }
Otherwise, our other input params might be `undefined` (just because of the way things are), so same deal, clear state and GTFO.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
>      }
And now, if we got here, we only want to call `setDAO` if we haven't done so yet for the given address

2024-03-29 03:33 UTC, adamgall commented on src/i18n/locales/en/common.json
> +  "badQueryParam2": "",
Better error strings for the various kinds of initial loading issues that might occur

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +      });
This was mostly just a flattening of logic and moving all non-get-data stuff out of this file and back into useDAOController. This useFractalNode hook is now only used for fetching stuff, no more checking if input data is valid, if it's in here (and not undefined) we should use it to go start fetching.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +      return;
If `skip` is true, that means there was an error with the address or formatting or we're on the wrong network. If addressPrefix of daoAddress is undefined, then damn the App is still standing up. In either case, just reset state and GTFO.

2024-03-29 03:33 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  const skip = invalidQuery || wrongNetwork;
This is fun. Do all the things needed to validate that:
1. we have a query string of the correct key
    - `dao`
2. the value of that key is formatted correctly
    - string-without-whitespace followed by ":" followed by string-without-whitespace
3. the ethereum address portion is formatted correctly
    - right length, checksum is valid if exists, etc
4. the network identified in the query param matches the network the app is currently on
    - so if the user is trying to load a `sep:0xabc` dao, the app must be on Sepolia

If any of those things fail, we don't try to load anything and show the appropriate error screen.

2024-03-29 03:36 UTC, adamgall commented
@Da-Colon @mudrila @tomstuart123 I have just pushed a bunch of fixes and nice QoL improvements, this is ready for review again.

2024-03-29 03:37 UTC, adamgall commented on src/types/fractal.ts
> +  daoNetwork: string | null;
Removed `daoNetwork` from `FractalNode`, now it only lives in Network state

2024-03-29 03:38 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +  }
Fixed

2024-03-29 03:38 UTC, adamgall commented on src/components/ui/menus/FavoritesMenu/FavoritesList.tsx
> +                network={addressPrefix}
Eh, not now. This seems like a big thing that I don't want us to tackle yet.

2024-03-29 03:39 UTC, adamgall commented on src/hooks/DAO/useDeployDAO.ts
> +  const { addressPrefix } = useNetworkConfig();
narrator: it was the proper place after all

2024-03-29 03:40 UTC, adamgall commented on src/components/pages/DaoDashboard/Info/index.tsx
> +              )}
This one actually wasn't fine. It was stopping the InfoCard on the DAO Dashboard page from rendering with the Loading icon, during initial DAO load. This has been updated to `DAO_ROUTES.proposals.relative(daoNetwork, daoAddress || '')`

2024-03-29 03:40 UTC, adamgall commented on src/components/pages/DaoDashboard/Info/index.tsx
> +              )}
This one actually wasn't fine. It was stopping the InfoCard on the DAO Dashboard page from rendering with the Loading icon, during initial DAO load. This has been updated to `DAO_ROUTES.proposals.relative(daoNetwork, daoAddress || '')`

2024-03-29 03:42 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +        setWrongNetwork(true);
This got refactored again in a later commit, go check another comment down below about it.

2024-03-29 03:42 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +      addressPrefix !== connectedAddressPrefix
This got refactored again in a later commit, go check another comment down below about it.

2024-03-29 12:12 UTC, tomstuart123 commented
Tried the new netlify link with 4 prior DAOs.

**TLDR**
- All mainnet prior DAO links worked when on the right chain already and were reformated correctly
- All sepolia prior dao links didn't work when on the right chain already and were given this
<img width="1233" alt="Screenshot 2024-03-29 at 13 08 53" src="https://github.com/decentdao/fractal-interface/assets/31554133/71944b05-f171-4f19-aefd-fe2a955bbd14">
- When on sepolia (different chain), all mainnet prior DAO links saw the below message which I believe is the intended error message 
<img width="1198" alt="Screenshot 2024-03-29 at 13 11 07" src="https://github.com/decentdao/fractal-interface/assets/31554133/35a3870b-7402-4011-a205-6235ee18c5b0">

**Mainnet DAO links tried**
1) Decent multisig (mainnet) - https://app.dev.fractalframework.xyz/daos/0xD26c85D435F02DaB8B220cd4D2d398f6f646e235
2) Decent's tokenvoting (mainnet) - https://app.dev.fractalframework.xyz/daos/0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064
3) Shutter's token voting  (mainnet)- https://app.dev.fractalframework.xyz/daos/0x36bD3044ab68f600f6d3e081056F34f2a58432c4
4) AwakeVCs - https://app.dev.fractalframework.xyz/daos/0xdD6CeFA62239272f1eDf755ba6471eacb7DF2Fa5

**Sepolia DAO links tried**
1) Myosin multisig - https://app.dev.fractalframework.xyz/home?dao=0xdef90A94273a1A1A72B33D39129fa41E6C08Be3a
2) One of my sepolia test dao s- https://app.dev.fractalframework.xyz/home?dao=0xA287241240B5C8fce743Fb291D4F38cD669298d4

2024-03-29 12:15 UTC, adamgall commented
@tomstuart123 the Sepolia links you tried are indeed formatted incorrectly. Notice how they are the new query params, but don't include the network prefix. This is invalid as per this new PR.

2024-03-29 12:33 UTC, tomstuart123 approved these changes

2024-03-29 12:40 UTC, adamgall commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> -  const safeAddress = fractalNode?.daoAddress;
Fixed

2024-03-29 20:30 UTC, Da-Colon approved these changes
Looks good thanks for the changes!

2024-03-29 20:30 UTC, merged