Replace BigNumber with bigint
decentdao/fractal-interface pull request #1523
Opened 2024-04-08 06:06 UTC by adamgall

This is to prepare for a codebase without `ethers.js` (v5, at least).

Next will be changes to the `fractal-contracts` repo / npm package, to publish plain `abi` objects instead of ethers-flavored TypeChain objects and types.

After that will be using `viem` contract objects in `fractal-interface` instead of the ethers-flavored TypeChain objects and types.

After that it'll be trivial to stop using the `ethers` `provider` and `signer`, and just use `viem`'s `publicClient` and `walletClient`.

After that we'll see the full power of `viem`'s RPC batching in action, giving (I hope to bob) extreme improvements in our network traffic performance.

2024-04-08 17:58 UTC, adamgall commented
# 🚨

This code very very likely breaks proposal templates, in which the JSON data on IPFS has keys named things like `bigNumberValue`. Since there are literally no more references to the string `BigNumber` in this code, then reading existing IPFS proposal templates is very very likely to fail. Need to go undo that IPFS proposal template key naming stuff specifically, and think through this a bit further.

2024-04-09 14:56 UTC, DarksightKellar approved these changes
Oh yeah this is looking sweet. I'm gonna go ahead and slap on that approve, I reckon any breaks, if relevant, should be addressed in a follow up

2024-04-10 02:29 UTC, adamgall commented on src/components/Proposals/ProposalSummary.tsx
> +      ? Number(votingStrategy.quorumPercentage!.value.toString())
Nah, u rite

2024-04-10 02:30 UTC, adamgall commented on src/components/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +    Number((((freezeProposalCreatedTime || 0n) + (freezeProposalPeriod || 0n)) * 1000n).toString()),
I knooo but I think it's necessary here

2024-04-10 02:37 UTC, adamgall commented on src/components/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +    Number((((freezeProposalCreatedTime || 0n) + (freezeProposalPeriod || 0n)) * 1000n).toString()),
Ok, got rid of one of them by removing that `.toString()`

2024-04-10 02:39 UTC, adamgall commented on src/components/Proposals/ProposalSummary.tsx
> +      ? Number(votingStrategy.quorumPercentage!.value.toString())
Fixed and pushed

2024-04-10 14:09 UTC, adamgall commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
> +      // @todo yo what is going on here
ah, I get what you're saying. thanks. I've changed my `@todo` into a `@dev` explaining this.

2024-04-10 14:15 UTC, adamgall commented on src/components/ui/links/EtherscanLinkERC20.tsx
> +      href={`${etherscanBaseURL}/${address === zeroAddress ? '' : 'token/'}${address}`}
yeah, good call. fixed and pushed

2024-04-10 19:42 UTC, Da-Colon reviewed
oof what a code review. Nothing beyond are earlier discussion which we have already fixed. A question about a few spots but just need to go click around the preview for approval

2024-04-10 19:42 UTC, Da-Colon commented on src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
> +
Its probably something in decodeTransaction function, of which I have yet to look at. But What is the reason for this change?

2024-04-10 19:42 UTC, Da-Colon commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +            proposalCreatedEvent.args.transactions.map(t => ({ ...t, value: t.value.toBigInt() })),
o huh, being done here too

2024-04-10 20:31 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +import type { Store } from '@netlify/blobs';
Yeah, every once in a while Typescript or ESLint (not sure who) will yell at me about it. It did while I was in this file, hence the update.

2024-04-10 20:37 UTC, adamgall commented on src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
> +
The `transactions` object, which comes directly from the TypeChain type from the Event type from our NPM export, has a `value` property of type `BigNumber`. The code here is to massage that into a `bigint` type so it fits in with this codebase.

This alludes to the next step in this bigger process, which is removing TypeChain exports from the NPM package (or at least, not using them in this `interface` repo any more). They all use `BigNumbers` internally and give responses in `BigNumber`.

2024-04-10 20:37 UTC, adamgall commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +            proposalCreatedEvent.args.transactions.map(t => ({ ...t, value: t.value.toBigInt() })),
Yep

2024-04-10 21:56 UTC, Da-Colon commented on src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
> +
Ah make sense

2024-04-10 22:04 UTC, Da-Colon requested changes
everything is looking good. moving around the app and different DAOs I don't seen anything out of place.

In Live Testing, I'm unable to create a new DAO, or a Sub DAO. The submit button is highlighted but clicking it does nothing with no errors in console or on screen.

Not really sure where this problem might be.

2024-04-11 17:35 UTC, adamgall commented on src/components/DaoCreator/formComponents/AzoriusTokenAllocations.tsx
> +                  (tokenAllocation.amount.bigintValue ?? 0n !== 0n)
You're absolutely right.

2024-04-11 17:38 UTC, adamgall commented on src/components/ui/links/EtherscanLinkERC20.tsx
> +  if (!address || address === zeroAddress) {
Why are we giving a special case to the zero address in anyway? 

Maybe, if the caller of this component wants to pass in the zero address, that's their decision, and we should just render the link as etherscan.io/token/0x000..000 and call it a day.

2024-04-11 17:55 UTC, adamgall commented on src/utils/shutter.ts
> -  const sigma = arrayify(BigNumber.from(randomBytes(32)));
It indeed seems like we don't need those extra functions and castings here:

```ts
import { init, encrypt } from "@shutter-network/shutter-crypto";
import { BigNumber, utils } from "ethers";

async function encryptWithShutter(
  choice: string,
  id: string,
  randBytes: Uint8Array
): Promise<string | null> {
  await init();

  const { arrayify, hexlify, toUtf8Bytes, formatBytes32String } = utils;

  const bytesChoice = toUtf8Bytes(choice);
  const message = arrayify(bytesChoice);
  const eonPublicKey = arrayify(
    "0x0e6493bbb4ee8b19aa9b70367685049ff01dc9382c46aed83f8bc07d2a5ba3e6030bd83b942c1fd3dff5b79bef3b40bf6b666e51e7f0be14ed62daaffad47435265f5c9403b1a801921981f7d8659a9bd91fe92fb1cf9afdb16178a532adfaf51a237103874bb03afafe9cab2118dae1be5f08a0a28bf488c1581e9db4bc23ca"
  );

  const is32ByteString = id.substring(0, 2) === "0x";
  const proposalId = arrayify(is32ByteString ? id : formatBytes32String(id));

  const sigma = randBytes;

  const encryptedMessage = await encrypt(
    message,
    eonPublicKey,
    proposalId,
    sigma
  );

  return hexlify(encryptedMessage) ?? null;
}

async function encryptWithShutterBN(
  choice: string,
  id: string,
  randBytes: Uint8Array
): Promise<string | null> {
  await init();

  const { arrayify, hexlify, toUtf8Bytes, formatBytes32String } = utils;

  const bytesChoice = toUtf8Bytes(choice);
  const message = arrayify(bytesChoice);
  const eonPublicKey = arrayify(
    "0x0e6493bbb4ee8b19aa9b70367685049ff01dc9382c46aed83f8bc07d2a5ba3e6030bd83b942c1fd3dff5b79bef3b40bf6b666e51e7f0be14ed62daaffad47435265f5c9403b1a801921981f7d8659a9bd91fe92fb1cf9afdb16178a532adfaf51a237103874bb03afafe9cab2118dae1be5f08a0a28bf488c1581e9db4bc23ca"
  );

  const is32ByteString = id.substring(0, 2) === "0x";
  const proposalId = arrayify(is32ByteString ? id : formatBytes32String(id));

  const randomBytesBigNumber = BigNumber.from(randBytes);
  const sigma = arrayify(randomBytesBigNumber);

  const encryptedMessage = await encrypt(
    message,
    eonPublicKey,
    proposalId,
    sigma
  );

  return hexlify(encryptedMessage) ?? null;
}

(async () => {
  const choice = "yes";
  const id = "0xabc123";
  const randBytes = utils.randomBytes(32);

  const originalCode = await encryptWithShutterBN(choice, id, randBytes);
  const newCode = await encryptWithShutter(choice, id, randBytes);

  console.log({ originalCode });
  console.log({ newCode });
  console.log(originalCode === newCode);
})();
```

outputs:

```
➜  testing123 npx ts-node src/arrayify.ts
{
  originalCode: '0x020c32d761d4872541d02e54c75a5816c85c99338a1554d585a2b96d6da527c30101f50c68bd8ecf3b74915632cbe19b9006ca2ff68790d8fd57dae2d0aa257e0a70de0a1965e02378f9dd8b9340d32a402f696078da6d23654f91d5f87050dd0a7c06d315b7daac41f554522db11d9f18a070b0862803034ca8b60f3e8e0bb9cdd9e4e7ba47a68f004915f660cb8afbfe8d1739713ebef0e4849113d1023ea591417d5eb9e9c7430f5fad174ef3cdb195f1a738cb1feb81344478067c323256'
}
{
  newCode: '0x020c32d761d4872541d02e54c75a5816c85c99338a1554d585a2b96d6da527c30101f50c68bd8ecf3b74915632cbe19b9006ca2ff68790d8fd57dae2d0aa257e0a70de0a1965e02378f9dd8b9340d32a402f696078da6d23654f91d5f87050dd0a7c06d315b7daac41f554522db11d9f18a070b0862803034ca8b60f3e8e0bb9cdd9e4e7ba47a68f004915f660cb8afbfe8d1739713ebef0e4849113d1023ea591417d5eb9e9c7430f5fad174ef3cdb195f1a738cb1feb81344478067c323256'
}
true
```

2024-04-11 18:00 UTC, adamgall commented
> everything is looking good. moving around the app and different DAOs I don't seen anything out of place.
> 
> In Live Testing, I'm unable to create a new DAO, or a Sub DAO. The submit button is highlighted but clicking it does nothing with no errors in console or on screen.
> 
> Not really sure where this problem might be.

@Da-Colon works for me. Can you try again?

2024-04-12 17:49 UTC, Da-Colon approved these changes
Weird nonce, thing that was mention in Slack, But the DAO creation has been fixed!

Was about to create parent and sub DAOs with all the numbers looking correct.

2024-04-12 18:08 UTC, merged