Enter snapshot space bug
decentdao/fractal-interface pull request #1564
Opened 2024-04-15 20:18 UTC by DarksightKellar

In this PR, we have made the assumption that all snapshot spaces linked in Fractal will necessarily be production snapshots. We're also assuming that the "snapshot space" input when creating or editing a DAO will always be an ENS name in the format `example.eth`.

To that end, the only url used to setup Apollo client has been set to `https://hub.snapshot.org/graphql`. This PR also fixes the broken snapshot link on the DAO info card.

NOTE: this will be impossible to test on testnets if the linked snapshot space is a testnet one

To consider: Should we hard enforce a NO-FULL-URL policy in the "snapshot space" inputs, IOW, ONLY accept `abc.eth` formats as inputs?

2024-04-15 21:11 UTC, adamgall commented
> To consider: Should we hard enforce a NO-FULL-URL policy in the "snapshot space" inputs, IOW, ONLY accept abc.eth formats as inputs?

FWIW, ENS names are not as simple as "abc.eth". There are a lot of forms they can take.

Play around with this tool: https://tools.ens.domains/check
Specifically, keep an eye on the "valid / invalid" tag that shows up in the "Normalized" section.

I think if we were to do what you're considering (which I do think we should do!), we should copy whatever is happening there. I would expect this is a good place to start: https://docs.ens.domains/resolution/names#normalize

2024-04-16 01:58 UTC, adamgall commented
@DarksightKellar I assume this PR close issue #1470?

2024-04-16 02:01 UTC, adamgall commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
Is this for some backwards compatibility reasons?

2024-04-16 08:21 UTC, DarksightKellar commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
Ah yes, I meant to add a comment here. But yeah, backward compatibility is the goal there

2024-04-16 11:45 UTC, adamgall commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
Can you explain how this backwards compatibility works?

2024-04-16 12:23 UTC, DarksightKellar commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
It's meant to maintain existing `snapshotURL`s that were entered and stored as full urls, instead of prepending the snapshot url to it, which would lead to an incorrect url: `https://snapshot.org/#https://snapshot.org/#example.eth`.

Aaaand now that I'm explaining it, I realise that initial assumption I'd made that ens names worked on mainnet continues to to plague me, and this won't work for fully qualified urls on prod.

Gonna update to `snapshotURL.startsWith('https://')`. So existing fully qualified urls of any form will be left alone, and ENS names entered after this PR will lead to the correct url.

At some point hopefully all DAOs will have updated their snapshot space and this can be removed. Orrrr we could not be backward compatible and communicate the necessary change with current users. Doubt that's the move to make though.

Have I missed anything?

2024-04-16 13:29 UTC, adamgall commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
We really only have _1_ testnet user, and they don't have a Snapshot space set. So I would say we do not need to be backwards compatible.

2024-04-16 14:20 UTC, adamgall commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
Ah right, mainnet users too. Well thankfully our only mainnet user that has their Snapshot set is us! And we can sneak in a fix for that during our initial set of proposals (cc @tomstuart123).

So I would say it's not necessary to build any backwards compatibility into this.

2024-04-16 14:25 UTC, DarksightKellar commented on src/components/ui/badges/Snapshot.tsx
> +    : `https://snapshot.org/#${snapshotURL}`;
Nice. Agreed then.

2024-04-16 14:47 UTC, adamgall requested changes
Looking good! Just one small syntax suggestion, and some questions.

A question I didn't leave in the code-level review, is: Could we update the state variable name `daoSnapshotURL` to something more accurate now, like `daoSnapshotENS`? Same with changing `snapshotURL` to `snapshotENS` on the `DAOEssentials` type.

IMO that seems appropriate for this PR.

2024-04-16 14:47 UTC, adamgall commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +      setSnapshotSpaceValid(!!value ? false : true);
Could the conditional check here happen up before the `try`, and early exiting the function if there's nothing in the value field?

For example

```ts
const handleSnapshotSpaceChange = (value: string) => {
    setFieldValue('essentials.snapshotURL', value, true);
    
    if (!value) {
        setSnapshotSpaceValid(true);
        return;
    }
    
    try {
        ens_normalize(value);
        setSnapshotSpaceValid(true);
    } catch (error) {
        console.log(error);
        setSnapshotSpaceValid(false);
    }
}
```

I think I prefer this style of coding. Does it do the same thing though?

2024-04-16 14:47 UTC, adamgall commented on src/components/pages/DaoSettings/components/Metadata/index.tsx
> -import { couldBeENS } from '../../../../../utils/url';
Looks like that helper function is used in a bunch of places in the app, blah.

It could be replaced with that `ens_normalize` function, right?

If so, can you please create an issue to replace `couldBeENS` with `ens_normalize`?

2024-04-16 15:42 UTC, tomstuart123 approved these changes
I just tested this with ENS at this DAO - https://deploy-preview-1564.app.dev.fractalframework.xyz/home?dao=eth:0xDBC4Ae5c0fdC921ee08B44031D6DA081De1d6485

Added Decent DAO's snapshot and then swapped it for Ehtlizards's snapshot.

Both worked. Feeling good. Thanks @DarksightKellar

2024-04-16 16:37 UTC, DarksightKellar commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +      setSnapshotSpaceValid(!!value ? false : true);
It does do the same thing. Early return looks nice. Will update and test

2024-04-16 22:54 UTC, adamgall approved these changes
@DarksightKellar doing a search in the codebase for "snapshoturl" still gives a bunch of hits, most of which can be updated.

The only place where we'll want to keep the "snapshoturl" nomenclature is right at the edges:
- outgoing: when building a transaction which includes the call to the "key value pairs" contract
- incoming: when consuming the "key value pairs" subgraph

Giving this an approval anyway, but it'd be nice to see the vast majority of those variables updated.

2024-04-17 13:16 UTC, DarksightKellar commented
Did a couple more rounds of quick tests after some cleanup. Merging now

2024-04-17 13:16 UTC, merged