Reskin/dao info cards
decentdao/fractal-interface pull request #1581
Opened 2024-04-19 17:30 UTC by DarksightKellar

Addresses #1562  + some refactoring where it made sense to me

I tried not to go wild on the refactoring and it's not a lot tbh, but feel free to push back on any of these updates if they seem problematic to you. I'll push back on the pushback if unconvinced though so full disclosure lol.

I'm gonna try and add comments to this PR on some of the refactor-specific diffs.

## Screenshots
<img width="1497" alt="Screenshot 2024-04-19 at 18 22 40" src="https://github.com/decentdao/fractal-interface/assets/7101382/a72fb6d7-ed7b-477a-9f7e-d5d80224ef66">

<img width="540" alt="Screenshot 2024-04-19 at 18 22 59" src="https://github.com/decentdao/fractal-interface/assets/7101382/82e93e5d-c358-403b-bc9e-374bb37e55f0">

<img width="558" alt="Screenshot 2024-04-19 at 18 23 17" src="https://github.com/decentdao/fractal-interface/assets/7101382/44bd8e53-9ac5-44f7-8877-1a18ef1afa52">

--- 

Pathetic menu reskin that needs more work. In a separate PR:
<img width="713" alt="Screenshot 2024-04-19 at 18 23 52" src="https://github.com/decentdao/fractal-interface/assets/7101382/512d708f-629b-400a-93f2-3e48cd39ca12">

2024-04-19 17:39 UTC, DarksightKellar commented on src/components/ui/cards/DAOInfoCard.tsx
> +    <Box {...rest}>
I've done a fair bit of UI component re-arranging here. Probably broke some edge case responsiveness somewhere else. Cross that bridge if we do get there.

2024-04-19 17:41 UTC, DarksightKellar commented on src/components/ui/icons/FavoriteIcon.tsx
> +          _active={{ color: 'lilac--2' }}
Lots of repeated `_hover` + `_active` additions (and similar styling code in general). If there's a better way to do this without changing the current codebase, I'd love to know. Otherwise this is something for future us to deal with

2024-04-20 04:05 UTC, Da-Colon requested changes
Looking good, few suggestions and comments

2024-04-20 04:05 UTC, Da-Colon commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +      }}
This also looked like Tertiary Button. so if `OptionMenu` takes the `as` prop I'd do that here too and set it to variant=`tertiary`

2024-04-20 04:05 UTC, Da-Colon commented on src/components/ui/menus/OptionMenu/OptionsList.tsx
>                    textStyle="text-base-mono-medium"
Left over old textStyle

2024-04-20 04:05 UTC, Da-Colon commented on src/components/ui/menus/OptionMenu/index.tsx
> +        bg="neutral-2" // neutral-2-84 ??
I'd grab the hex for now, and we can try to get this color in the next publish

2024-04-20 04:05 UTC, Da-Colon commented on src/components/ui/utils/Sort.tsx
>        color="grayscale.100"
leftover old color

2024-04-20 04:05 UTC, Da-Colon commented on src/components/ui/menus/OptionMenu/OptionsList.tsx
>                      iconColor="black.900"
left over old color

2024-04-22 17:38 UTC, DarksightKellar commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +      }}
Perfect, thanks for this. I can't seem to find the "tertiary" variant anywhere though. All similar components are marked "ghost".

2024-04-22 17:43 UTC, DarksightKellar commented on src/components/ui/badges/Snapshot.tsx
> +const SnapshotIconSVG = () => (
Ah, that's good to know. I'm gonna leave as is in this case, since it's like 90% similar and there's no argument for one over the other (in this case).

2024-04-22 21:20 UTC, adamgall commented on src/components/ui/menus/OptionMenu/OptionsList.tsx
>                    textStyle="text-base-mono-medium"
@DarksightKellar should this be removed?

2024-04-22 21:23 UTC, adamgall commented
Shoot I did not mean to just delete @Da-Colon 's comment. Gonna put it back, I remember what it was about.

2024-04-22 21:24 UTC, adamgall commented on src/components/ui/menus/OptionMenu/OptionsList.tsx
>                    textStyle="text-base-mono-medium"
Originally a comment from @Da-Colon, which I accidentally deleted:

> Don't forget to remove this old `textStyle` (or something like that).

Then, @DarksightKellar, you "resolved" this comment without doing anything about it.

Do we need to remove it?

2024-04-22 21:24 UTC, adamgall approved these changes
Leaving an approval because we just need to play fast and get big bulks of code merged quickly, then worry about the details later.

2024-04-23 08:32 UTC, DarksightKellar commented on src/components/ui/menus/OptionMenu/OptionsList.tsx
>                    textStyle="text-base-mono-medium"
Yes it should be removed. Dunno how that happened tbh. Maybe I accidentally reverted while I was staging. Thanks for catching this!

I'm actually thinking of raising a separate PR to remove ALL (non-reskin) textStyles across the app.

2024-04-23 15:24 UTC, merged