Replace ethers utils
decentdao/fractal-interface pull request #1597
Opened 2024-04-23 19:45 UTC by mudrila

Closes #1599

2024-04-23 20:20 UTC, adamgall commented
@mudrila would you please create an issue for this specific PR? Thanks

2024-04-24 15:17 UTC, adamgall requested changes
Lots and lots of comments!!

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +  private readonly predictedSafeAddress: Address;
Compiler telling me this is never used... can we delete it?

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      tokenImportAddress! as Address,
Two things:
1. please no `!`
2. please use `getAddress` instead of casting `as Address`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      ) as Hash;
Please use `isHex()` instead of casting `as Hash`, and error / early exit if false.

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      this.azoriusContracts!.votesERC20WrapperMasterCopyContract.address.slice(2) as Address,
See previous comment, but we should _not_ be slicing the `0x` off of an Address, then calling it an `Address`.

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        tokenAllocationsOwners as Address[],
map `getAddress()`. Or even better, make that `tokenAllocationOwners` property be an array of `Address` in the first place, probably in the `calculateTokenAllocations` function.

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      ]) as Hash;
use `isHex()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        this.predictedTokenAddress as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      ]) as Hash;
`isHex()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      this.azoriusContracts!.claimingMasterCopyContract.address.slice(2) as Address,
no slicing an Address then calling it an Address.

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        ) as Hash;
`isHex()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        this.azoriusContracts!.linearVotingMasterCopyContract.address.slice(2) as Address,
Nope plz no slice here

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +          this.safeContract.address as Address, // owner
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        ) as Hash;
`isHex()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        this.safeContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      ) as Hash;
`isHex()`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        Number(azoriusGovernanceDaoData.executionPeriod), // execution period in blocks
Perhaps these types should be `numbers` already in the interfaces, not `bigint`

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      this.azoriusContracts!.fractalAzoriusMasterCopyContract.address.slice(2) as Address,
no slice here plz

2024-04-24 15:17 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +      from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +  private freezeVotingCallData: Hash | undefined;
`Hex` type please

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +  private freezeGuardCallData: Hash | undefined;
`Hex`

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +      freezeVotesMasterCopyContract.address.slice(2) as Address,
No slice here plz

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +      from: this.baseContracts.zodiacModuleProxyFactoryContract.address as Address,
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +      this.getGuardMasterCopyAddress().slice(2) as Address,
no slice here plz

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +          this.azoriusAddress as Address, // Azorius
`getAddress()`

2024-04-24 15:17 UTC, adamgall commented on src/models/FreezeGuardTxBuilder.ts
> +    ) as Hash;
`isHex()` then error / early exit if not.

2024-04-26 04:45 UTC, jxom commented on src/components/DaoCreator/formComponents/AzoriusNFTDetail.tsx
> +          ]);
It sure will!

https://viem.sh/docs/clients/public#eth_call-aggregation-via-multicall

2024-04-26 18:18 UTC, adamgall commented on src/assets/abi/SafeL2.ts
Yes, I think it would be best to keep the name as `GnosisSafeL2`

2024-04-26 18:20 UTC, adamgall commented on src/components/DaoCreator/formComponents/AzoriusNFTDetails.tsx
> +                nftError?.tokenAddress && nft.tokenAddress?.length
I follow that

2024-04-26 18:25 UTC, adamgall commented on src/components/DaoCreator/hooks/usePrepareFormData.ts
> +              address = (await signer!.resolveName(nft.tokenAddress!)) as Address;
Next, please remove figure out how to remove the `!`s in this line.

FYI, I'm going to start being more demanding about being explicit in the codebase about when things may or may not be `null`/`undefined`. We're losing the safety guarantees of typescript with that damned `!`

2024-04-26 18:45 UTC, adamgall commented on src/hooks/DAO/loaders/useGovernanceContracts.ts
> +          votesTokenContractAddress = lockedTokenAddress as Address;
Can you please replace lines 78-82 with the following? I find it a bit easier to read and reason about:

```ts
        let lockedTokenAddress = undefined;
        try {
          lockedTokenAddress = (await possibleLockRelease.read.token()) as Address;
        } catch {
          // no-op
          // if the underlying token is not an ERC20Wrapper, this will throw an error,
          // so we catch it and do nothing
        }
```

2024-04-26 18:52 UTC, adamgall commented on src/helpers/crypto.ts
> +  });
Oh I'm not "suggesting" it! Just mentioning that both compile, and I wonder if there's a difference between the two.

Unresolving this conversation so we don't lose it, cause this definitely needs to be tested more.

2024-04-26 19:43 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +          Number(azoriusGovernanceDaoData.votingPeriod),
Ok, I smell some bad patterns around here. Always a red flag if we're hard casting from `bigint` to `number`, means our types are fucked somewhere. We can revisit this later though.

2024-04-26 19:47 UTC, adamgall commented on src/models/AzoriusTxBuilder.ts
> +        Number(azoriusGovernanceDaoData.executionPeriod), // execution period in blocks
Same comment as previous -- here be dragons.

2024-04-26 20:04 UTC, adamgall commented on src/types/transaction.ts
>    data: string;
How much more work would it take to narrow these types down to:

```ts
value: bigint;
data: Hex;
```

2024-04-26 20:05 UTC, adamgall commented
Alright @mudrila , I just went through everything.

- Unresolved a couple of conversations.
- Left replies on a couple of conversations.
- Created a couple new comment threads.

Please have a look through all of the _unresolved_ conversation threads.

This is pretty close!

2024-04-29 18:36 UTC, adamgall reviewed
Looking good man! I'll give this an approval as soon as the remaining manual testing from [this comment](https://github.com/decentdao/fractal-interface/pull/1597#discussion_r1580928159) is completed.

2024-04-29 18:36 UTC, adamgall commented on src/types/transaction.ts
>  export interface SafeAPITransaction {
Looks like this interface isn't used anywhere. Can delete it?

2024-05-02 17:35 UTC, adamgall commented on src/helpers/crypto.ts
> +  });
@mudrila you were right, I was wrong!

```ts
import { getAddress, hashTypedData } from "viem";

const domain = {
  verifyingContract: getAddress("0xfcf7a2794D066110162ADdcE3085dfd6221D4ddD"),
  chainId: 1,
};
const types = {
  SafeTx: [
    { type: "address", name: "to" },
    { type: "uint256", name: "value" },
  ],
};
const primaryType = "SafeTx";
const message = {
  to: getAddress("0xfcf7a2794D066110162ADdcE3085dfd6221D4ddD"),
  value: 1000000000000000000n,
};

// this throws an error
console.log(
  hashTypedData({
    domain: domain,
    types: types,
    primaryType: primaryType,
    message: { message },
  })
);

// this does not throw an error
console.log(
  hashTypedData({
    domain: domain,
    types: types,
    primaryType: primaryType,
    message: { ...message },
  })
);
```

Remove the `...` throws an error. With the specific way this code is set up, we do need to destructure the `safeTx` object here. Nice job sir.

2024-05-04 00:18 UTC, merged