Reskin/sidebar
decentdao/fractal-interface pull request #1605
Opened 2024-04-24 20:56 UTC by adamgall

2024-04-26 13:39 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLink.tsx
> +  Icon: JSX.Element;
I'll use `ReactElement`, some light research suggests that's the best option. Thanks for the callouts.

2024-04-26 13:40 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLink.tsx
> +    <Box py={3}>
Yes, probably. I did notice they were becoming very similar. I'll take a stab at combining them.

2024-04-26 13:42 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLinks.tsx
> +          Icon={<Question size={24} />}
I could use another pair of eyes on this, it's harder for me to implement than I was expecting.

2024-04-26 13:42 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLinks.tsx
> +            pl="11px"
Oh man you're telling me. Let's go over this in realtime too.

2024-04-26 13:51 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLinks.tsx
> +          Icon={<Question size={24} />}
Fixed, thanks for your help!

2024-04-29 21:07 UTC, adamgall commented
@DarksightKellar @mudrila I've addressed your comments, and marked this PR ready for review

2024-04-30 11:29 UTC, DarksightKellar approved these changes

2024-04-30 13:07 UTC, adamgall commented on src/components/ui/page/Header/index.tsx
> +              bg="#221D25D6"
Correct, this color includes an alpha channel. We have some "What Alpha" and "Black Alpha" colors defined in `decent-ui`, but not this neutral color. I've added a comment here in the codebase.

2024-04-30 13:13 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLink.tsx
> +  t: TFunction<'navigation', undefined>;
Two things:

1. I meant for line 14 to be more generic than that. It should actually just be
   ```ts
   t: TFunction;
   ```
   I just pushed an update.
2. I did it like this just to cut down on the number of `useTranslation` invocations happening in this file (to just one). Everything in this file is using the `navigation` translation namespace, so invoking the hook once and then prop drilling the result seemed right to me, for DRY reasons.

2024-04-30 13:16 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLink.tsx
> +        style={{ display: 'block', paddingTop: '0.75rem', paddingBottom: '0.75rem' }}
I might need your help with this one... The `Link` component here is from `react-router-dom`, not `chakra-ui`, and so doesn't have any `paddingTop` etc properties on it. I don't really know how else to add styles to this (I want to literally make the rendered anchor tag bigger) without either doing these inline styles, or defining a CSS class somewhere.

2024-04-30 13:21 UTC, adamgall commented on src/components/ui/page/Navigation/NavigationLink.tsx
> +        style={{ display: 'block', paddingTop: '0.75rem', paddingBottom: '0.75rem' }}
Anchor tags seem to not be `block` by default.

---

```ts
style={{ display: 'block', paddingTop: '0.75rem', paddingBottom: '0.75rem' }}
```
<img width="73" alt="Screenshot 2024-04-30 at 9 19 45 AM" src="https://github.com/decentdao/fractal-interface/assets/706929/f9db83a1-4e30-44b1-bca0-90d7dabc0b7c">

---

```ts
style={{ paddingTop: '0.75rem', paddingBottom: '0.75rem' }}
```
<img width="73" alt="Screenshot 2024-04-30 at 9 20 19 AM" src="https://github.com/decentdao/fractal-interface/assets/706929/bb423f47-762c-459c-9c4c-0dacefc33f01">

---

And can you help me with whatever it is you're suggesting to not use inline styles? I guess I'm not sure what approach you're suggesting.

2024-04-30 14:14 UTC, nicolaus-sherrill requested changes
This is looking great! 

I was having some weird issues with the component when I first pulled up the deploy preview (cursor glitching, needing to click to expand) but was unable to recreate once I reloaded and left the page open for a bit.

I don't see the hover, pressed, or active states active here yet, captured in this screen shot and recording.

<img width="532" alt="Screenshot 2024-04-30 at 9 13 23 AM" src="https://github.com/decentdao/fractal-interface/assets/62394931/f1e8b154-6354-4b9a-ab0e-21b8f2d8550d">

https://github.com/decentdao/fractal-interface/assets/62394931/8cf95c68-cf03-484e-adaa-5a43588b58b4

2024-04-30 14:36 UTC, adamgall commented
> This is looking great!
> 
> I was having some weird issues with the component when I first pulled up the deploy preview (cursor glitching, needing to click to expand) but was unable to recreate once I reloaded and left the page open for a bit.
> 
> I don't see the hover, pressed, or active states active here yet, captured in this screen shot and recording.
> 
> <img alt="Screenshot 2024-04-30 at 9 13 23 AM" width="532" src="https://github.com/decentdao/fractal-interface/assets/62394931/f1e8b154-6354-4b9a-ab0e-21b8f2d8550d">
> 
>  Screen.Recording.2024-04-30.at.9.06.56.AM.mov

@nicolaus-sherrill sorry, where is that figma showing the hover and active states?

2024-04-30 17:19 UTC, merged