Memoize reached quorum
decentdao/fractal-interface pull request #1736
Opened 2024-05-09 13:28 UTC by DarksightKellar

`votesSummary` is apparently something that _might_ be undefined, as implied by existing undefined checks. I've added those checks to `reachedQuorum` as well. 

Might possibly address https://github.com/orgs/decentdao/projects/32/views/19?pane=issue&itemId=62337055

2024-05-09 14:02 UTC, DarksightKellar commented on src/utils/hierarchy.ts
> -type DAOQueryNode = Pick<
Should this code even be in the reskin branch?

2024-05-09 15:30 UTC, adamgall commented on src/utils/hierarchy.ts
> -type DAOQueryNode = Pick<
It makes sense to me that it's still here -- when I had removed it on the call with us on Tuesday, it was during a merge conflict resolution session. Yesterday I "undid" that merge, so this code got put back.

2024-05-09 15:31 UTC, adamgall commented
@DarksightKellar why do you think this would address #1716 ?

2024-05-09 15:40 UTC, DarksightKellar commented
> @DarksightKellar why do you think this would address #1716 ?

I goofed up. I've updated the description to the correct issue   I meant to ref

2024-05-09 16:18 UTC, adamgall requested changes
Chatted with the team about this.

The issue is _very likely_ that for a split second there are some data loading issues, and the app thinks the given dao/proposal is a multisig, when in fact it's an Azorius, and the currently rendered QuorumBadge goes to re-render, and we force its type to AzoriusProposal, but it isn't at that split second, and the app crashes.

So,

for now, we can just bandaid fix this. Move the bandaid up as far as possible, maybe likely just up into the ProposalCard.

The better fix is to rearchitect and refactor our typing system and data loading system. But that's a project for another day.

2024-05-09 18:36 UTC, DarksightKellar commented
@adamgall Pushed an update. Because `QuorumBadge` now requires an `AzoriusProposal`, the undefined checks are no longer necessary, so they've been removed. 

The `as AzoriusProposal` has simply moved further up to the `ProposalCard` though. But that is more confident type assertion. Any higher up and the proposal can only be a `FractalProposal` until context determines what it actually is.

Further thoughts: I dunno that much can be done about rearchitecting the typing system (in this context) tbh. Probably makes more sense to focus (when we do get to it) on figuring out the data loading flow that's causing this state disconnect.

2024-05-09 19:10 UTC, DarksightKellar commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  const isAzoriusProposal = !!(proposal as AzoriusProposal).votesSummary;
The thing is, it's not absolutely certain that `proposal` _will be_ an `AzoriusProposal`. 

There's no point in making that assumption early on, only to discover that `azoriusProposal` doesn't in fact have a `.votesSummary` on attempting to pass it to `QuorumBadge` (so it's not actually an `AzoriusProposal`), and then just not using `azoriusProposal` at all.

2024-05-09 20:06 UTC, adamgall commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  const isAzoriusProposal = !!(proposal as AzoriusProposal).votesSummary;
@mudrila i'm confused about what you're saying. Where do you see `proposal as AzoriusProposal` twice?

2024-05-09 20:14 UTC, adamgall requested changes

2024-05-09 20:14 UTC, adamgall commented on src/components/Proposals/ProposalSummary.tsx
> +  );
I like the code you wrote in QuorumBadge to turn these nested ternaries into various if blocks. Can you do that here too?

2024-05-09 20:14 UTC, adamgall commented on src/components/Proposals/ProposalSummary.tsx
> +
For the sake of trying to isolate where the bug actually appears, can you please undo this?

2024-05-10 12:55 UTC, adamgall approved these changes

2024-05-10 12:58 UTC, merged

2024-05-10 13:03 UTC, DarksightKellar commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  const isAzoriusProposal = !!(proposal as AzoriusProposal).votesSummary;
It's further down, passing proposal as a prop to QuoromBadge

2024-05-10 13:07 UTC, adamgall commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +  const isAzoriusProposal = !!(proposal as AzoriusProposal).votesSummary;
Ah ok, thanks. Regardless, I implemented the changes I requested in my review and merged this branch already!