Fix sizes and positionings of icons in DAO Home Info card
decentdao/fractal-interface pull request #1771
Opened 2024-05-11 03:04 UTC by adamgall

Fixes #1685 
Fixes #1706 

Followed designs laid out here: https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?type=design&node-id=0-1&mode=design&t=8YsCQEATr7eLrXaT-0

2024-05-11 18:48 UTC, xraystyle1980 requested changes
Thanks @adamgall 
Can you update the padding to 4px instead of 8px? (apologies if this was not reflected in the handoff. [Should be accurate now](https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?m=auto&node-id=0%3A1&t=Asu3Cx05Hpfshpr1-1)) 
Icon size is good at 20px. 

[In Design System](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=2280%3A4470&t=vVvAMhuUVwVMWYdf-1)

Positioning looks good on desktop
Positioning looks good on mobile albeit mobile is still italicized

2024-05-11 19:18 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +          padding={variant === 'lil-smaller' ? '0.3rem' : '0.5rem'}
Nope, sorry, this actually was just reverted. See comment by Trice below

2024-05-11 19:19 UTC, adamgall commented
@xraystyle1980 I have reverted so that both locations (other than the header) where that Favorites button appears, is the same size: 20x20 icon, 28x28 button

2024-05-11 19:36 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +        <Button
Understood. I'll hold on merging this.

2024-05-13 14:16 UTC, DarksightKellar reviewed
Holding off approval pending decent-ui updates

2024-05-14 14:39 UTC, tomstuart123 commented
won't comment on exact pixel sizing... but looks good to me at first glance

It says above already merged but will approve anyway just in case

2024-05-14 14:39 UTC, tomstuart123 approved these changes

2024-05-14 17:13 UTC, Da-Colon commented
When you get this updated with latest from root. I'll start the secondary work on the hierarchy card.

2024-05-14 18:34 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +        <Button
@mudrila yes sir!

2024-05-14 18:51 UTC, adamgall commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
>        buttonAs={Button}
Unfortunately, still need these `buttonProps`. Probably because this exists in an `OptionMenu`, not a `Button`

2024-05-14 18:51 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +        <Button
Was able to clean this up. Thank you!

2024-05-14 18:52 UTC, adamgall commented
@decentdao/engineering looking for more review plz

2024-05-14 19:01 UTC, adamgall commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +        p: '0.25rem',
You are correct, `size: 'icon-sm'` doesn't work, we need the `p: 0.25rem` in `buttonProps` to get the correct icon button size here.

2024-05-14 19:02 UTC, merged