`Reskin` - remove module transactions
decentdao/fractal-interface pull request #1776
Opened 2024-05-11 22:08 UTC by mudrila

Closes #1712

2024-05-13 14:23 UTC, DarksightKellar requested changes

2024-05-13 14:23 UTC, DarksightKellar commented on src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +        // https://github.com/decentdao/fractal-interface/issues/1712
Given that I still lack quite a bit of app-wide context, take this with a pinch of salt, but should we not be _ripping_ out module transactions from the app instead of having them around in memory but never to be displayed?

2024-05-13 14:46 UTC, tomstuart123 commented
@mudrila / @DarksightKellar dumb question, what's the quickest way for me to replicate these 'module txs' in the app (i.e. so that I can make sure they don't appear)

Create DAO flow?

2024-05-14 00:16 UTC, Da-Colon approved these changes
Fantastic, Ship it.

2024-05-14 11:47 UTC, DarksightKellar approved these changes

2024-05-14 14:23 UTC, tomstuart123 commented
still can't replicate this in the UI ( I tried recommended DecentDAO but the module Txs weren't there). Recommend, devs just approve this one so I don't become a blocker

2024-05-14 14:31 UTC, merged

2024-05-27 16:12 UTC, adamgall commented on src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +        // https://github.com/decentdao/fractal-interface/issues/1712
Coming back to this. While working on https://github.com/decentdao/decent-interface/issues/1675 I'm realizing that, while trying to figure out the "total number of proposals", there's a discrepancy with the number of proposals we're showing in the list, and the number of proposals that are in memory.

As part of that issue, i'm going to update our state to _totally remove these module transactions_ from state, so that it's easier to reason about what the "total number of proposals" are.