Moves ProposalCountdown from the Badge component
decentdao/fractal-interface pull request #1786
Opened 2024-05-14 19:53 UTC by Da-Colon

Separate the `ProposalCountdown`  from the `Badge` component

![image](https://github.com/decentdao/fractal-interface/assets/38386583/521f1395-639e-4b54-b3ee-61543ecb449b)
![image](https://github.com/decentdao/fractal-interface/assets/38386583/2ac4a867-e2a1-4917-9c59-ca9a5dfc94ad)
![image](https://github.com/decentdao/fractal-interface/assets/38386583/0ede6244-f8ce-4a17-a1df-5bc27ad3643f)

Fixes #1695

2024-05-14 20:12 UTC, adamgall requested changes
I think you can cleanup the props to `ProposalCountdown` a bit.

At first glance, `textStyle` will _always` be `label-base`, so can probably remove it and inline the style.

The `showIcon` prop is only `true` in one usage of this component... Do we really need it?

Etc.

2024-05-15 00:27 UTC, Da-Colon commented
> I think you can cleanup the props to `ProposalCountdown` a bit.
> 
> At first glance, `textStyle` will _always`be`label-base`, so can probably remove it and inline the style.
> 
> The `showIcon` prop is only `true` in one usage of this component... Do we really need it?
> 
> Etc.

Updated to remove the textStyle. But the other two props `textColor` and `showIcon` are both being used.

These defaults seem to mainly be for the the `TxActions` component for the Timelock on the Button.

2024-05-15 11:29 UTC, DarksightKellar approved these changes

2024-05-15 14:02 UTC, Da-Colon commented on src/components/Proposals/ProposalInfo.tsx
> +          showIcon={false}
IMO I think it will be better than this comment creates an issue that is taken on when design can get a hold of it rather than preempt sniping, thoughts?

2024-05-15 15:39 UTC, adamgall commented
To @Da-Colon's point, The "logo" discussion doesn't have anything to do with countdown timer for active proposal and the "Active" chip. sorry for derailing this PR.

2024-05-15 16:41 UTC, tomstuart123 commented
tested for both vote period and timelock. both work really well

Thanks @Da-Colon 

(note I did find an issue but not related to this PR)

2024-05-15 16:41 UTC, tomstuart123 approved these changes

2024-05-15 16:52 UTC, merged