`Reskin` 1773 dao hierarchy node updates
decentdao/fractal-interface pull request #1788
Opened 2024-05-14 22:24 UTC by Da-Colon

Adds Hover states to Hierarchy card

Allows for children components to be clickable.

### Note
- I got everything to work here but did notice that the FavoriteIcon toggle is kinda a precise click. its pretty easy to navigate by mistake. But its really not too bad. 

Closing #1773

2024-05-15 11:06 UTC, DarksightKellar approved these changes
LGTM.

The hover design got a minor update -- I've gone ahead and implemented it in a new commit.

2024-05-15 14:12 UTC, Da-Colon reviewed
Thanks for the review @mudrila

2024-05-15 14:12 UTC, Da-Colon commented on src/components/ui/cards/DAONodeInfoCard.tsx
> +    <Link
Link 
  as RouterLInk gives it access to the Chakra Theme. so this looks right. As far as using `as` RouterLink. Just using the pattern I saw in place already.

2024-05-15 14:12 UTC, Da-Colon commented on src/components/ui/cards/DAONodeInfoCard.tsx
> +        _hover={!isCurrentDAO ? { bg: 'neutral-4' } : {}}
yeah Link handles this.

2024-05-15 14:12 UTC, Da-Colon commented on src/components/ui/cards/DAONodeInfoCard.tsx
> +        <VStack
preexisting condition, I didn't really change anything here. and mobile doesn't seem to have any issues

2024-05-15 14:12 UTC, Da-Colon commented on src/components/ui/cards/DAONodeInfoCard.tsx
> +              zIndex={3}
ah mistake good eye

2024-05-15 14:12 UTC, Da-Colon commented on src/components/ui/links/AddressCopier.tsx
> +    <Box
> I think what we can do instead is <ExternalLink as={Box} and all the styles gonna be applied. Can you give it a try?

I don't believe `as={Box}` is the proper solution that can be confusing if all we are trying to do is keep styling from being duplicated. 

> Also, it probably makes most sense to use CeleryButtonWithIcon - so that we're rendering Button into DOM to keep proper semantic

I'll take a look at this component. But other wise I can always create a `styled component` that both the `ExternalLink` and `AddressCopier` use rather than relying on a styled `<a>`

2024-05-15 16:01 UTC, tomstuart123 commented
hover feels fire to me @Da-Colon thanks so much

2024-05-15 16:02 UTC, tomstuart123 approved these changes

2024-05-15 17:06 UTC, adamgall requested changes

2024-05-15 17:06 UTC, adamgall commented on src/components/ui/links/AddressCopier.tsx
> +    <Box
My opinion is that we should not be rendering an `a` tag for this address copier.

---

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

> The `<a>` HTML element (or anchor element), with its href attribute, creates a hyperlink to web pages, files, email addresses, locations in the same page, or anything else a URL can address.

This Address Copier does not fit within that definition of "anything a URL can address".

---

Further down: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#onclick_events

> Anchor elements are often abused as fake buttons by setting their href to # or javascript:void(0) to prevent the page from refreshing, then listening for their click events .
>
> These bogus href values cause unexpected behavior when copying/dragging links, opening links in a new tab/window, bookmarking, or when JavaScript is loading, errors, or is disabled. They also convey incorrect semantics to assistive technologies, like screen readers.
>
> Use a <button> instead. **In general, you should only use a hyperlink for navigation to a real URL.**

2024-05-15 17:06 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +          }}
Why was this necessary?

2024-05-15 19:15 UTC, Da-Colon commented on src/components/ui/links/AddressCopier.tsx
> +      borderRadius="625rem"
I'll check this when I get home but I shouldn't have touched any existing code in this component accept for removing the ExternalLink component. Weird.

2024-05-15 21:07 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +          }}
hmmmmm ok

2024-05-15 21:48 UTC, Da-Colon commented on src/components/ui/cards/DAONodeInfoCard.tsx
> +        <VStack
Yeah, I have the same issue with these `VStack` and `HStack` not a fan. but there doesn't seem to be an issue to leave this as is for now.

2024-05-15 21:53 UTC, Da-Colon commented on src/components/ui/links/AddressCopier.tsx
> +    <Box
Good call, switched it out with CeleryButtonWithIcon

2024-05-15 21:58 UTC, Da-Colon commented on src/components/ui/links/AddressCopier.tsx
> +      borderRadius="625rem"
To answer your question in the figma (https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?node-id=2248-24839&t=5IKSu7evpRPLhVv4-4)

This has a border radius of 'full' which looks to be `9999px` which to be exact is `624.9375rem` so looks like it was rounded up to `625rem`

2024-05-15 22:27 UTC, adamgall commented on src/components/ui/links/AddressCopier.tsx
> +      borderRadius="625rem"
`borderRadius='full'` should work, no?

2024-05-15 22:54 UTC, Da-Colon commented on src/components/ui/links/AddressCopier.tsx
> +      borderRadius="625rem"
for Chakra-UI, full === "100%" which means something different

2024-05-15 23:06 UTC, adamgall commented on src/components/ui/links/AddressCopier.tsx
> +      borderRadius="625rem"
Aren't we after a pill shape here? If so, afaik, `border-radius: 100%` is what we want.

2024-05-15 23:29 UTC, adamgall commented on src/components/ui/links/AddressCopier.tsx
> +      borderRadius="625rem"
yeah maybe this is just the way to do it lol

https://stackoverflow.com/questions/18794947/capsule-shape-using-border-radius-without-a-set-width-or-height#comment27716432_18795153

2024-05-15 23:31 UTC, adamgall approved these changes
love it

2024-05-16 11:57 UTC, xraystyle1980 reviewed
Hierarchy looks good 👍 
Request:  can you let the breadcrumbs go full width?
![CleanShot - Arc - 2024-05-16@2x](https://github.com/decentdao/fractal-interface/assets/18615633/5e23d4d1-c2b3-4aa4-9c98-03548fafa9b5)

2024-05-16 13:03 UTC, merged