`Reskin` | Implement search safe redesign
decentdao/fractal-interface pull request #1834
Opened 2024-05-20 16:03 UTC by DarksightKellar

Addresses #1800. Also removed the search bar from top nav. Other top nav updates will happen in a follow PR on #1802

2024-05-21 04:30 UTC, Da-Colon approved these changes
No Comments, UI/code looks/works great

2024-05-21 04:30 UTC, Da-Colon commented on src/components/ui/menus/DAOSearch/index.tsx
> +          boxShadow="0px 0px 0px 1px #100414, 0px 0px 0px 1px rgba(248, 244, 252, 0.04) inset, 0px 1px 0px 0px rgba(248, 244, 252, 0.04) inset" // T_T
// T_T 😄

2024-05-21 04:30 UTC, Da-Colon commented on src/components/ui/modals/ModalProvider.tsx
> +        modalContent = <DelegateModal close={closeModal} />;
good call with the rename

2024-05-21 04:30 UTC, Da-Colon commented on src/constants/common.ts
> +export const SIDEBAR_WIDTH = '4.25rem';
💯

2024-05-21 14:51 UTC, adamgall requested changes
Small change request

2024-05-21 20:21 UTC, tomstuart123 commented
I really like this implementation. Thanks @DarksightKellar

2024-05-21 20:21 UTC, tomstuart123 approved these changes

2024-05-21 20:46 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
> +  onClick?: () => void;
edit: yes it is, in another file

2024-05-21 21:36 UTC, adamgall requested changes

2024-05-22 00:51 UTC, Da-Colon commented on src/components/ui/modals/ModalBase.tsx
> +      size={props.isFullscreen ? 'container.xl' : 'lg'}
@DarksightKellar We should be able to remove this or change it to 'full' now with the other adjustments it should work now.

2024-05-22 09:55 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
>        isCentered
The goal of the `isFullscreen` prop isn't to dictate centering, it's really to remove the default modal container styling applied to the modal content passed into `ModalBase` (see code from 42 which applies the default modal content box styling)

2024-05-22 10:00 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
> +      size={props.isFullscreen ? 'container.xl' : 'lg'}
Using `full` pushes the search bar too high up. That said, I also don't see any difference when simply using `lg`. Must've been some other styling when we were trying to get this right that fixed this lol. Ah, CSS. Love it.

I'll update to `lg`

2024-05-22 10:11 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
> +          mx={{ base: '1rem', md: '1.5rem' }}
Barely perceptible, but it's there:

<img width="1399" alt="Screenshot 2024-05-22 at 11 09 20" src="https://github.com/decentdao/fractal-interface/assets/7101382/51c7dce9-8568-48a2-8f33-60493614d9e8">

<img width="1363" alt="Screenshot 2024-05-22 at 11 09 39" src="https://github.com/decentdao/fractal-interface/assets/7101382/c396a548-f281-4d33-ab30-c06c8906f566">

2024-05-22 10:13 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
> +          maxW={`calc(80rem + ${SIDEBAR_WIDTH})`}
Yah, good call

2024-05-22 10:45 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
> +          maxW={`calc(80rem + ${SIDEBAR_WIDTH})`}
Would've been real nice if that worked out (I tried moving all props, and then just `mt`, to `DaoSearch` which is what ModalProvider is set up to return for the search input), but that just shoved the input further down off centre. 

Changing `isCentered` to false didn't help much -- I then had to reduce the top margin to `5rem` via trial and error to fit the look, after which the click-to-dismiss area above the input stopped working (using either `mt` or `pt`)

I think I get where you're coming from though. Specifically that `mt` is technically a search-box-fullscreen-modal-specific styling and may not apply to future users of the `isFullscreen` prop (which itself is a bit of a misnomer, and actually is more of a I-will-supply-my-own-base-box-styling prop). 

Probably a more effective thing to do would be to allow custom modal-base-container styling to be passed in.

2024-05-22 12:41 UTC, adamgall commented on src/components/ui/modals/ModalProvider.tsx
> +  isFullscreen: boolean;
i would argue that `isFullscreen` is the appropriate spelling, because "fullscreen" is one word. See https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

2024-05-22 12:56 UTC, adamgall commented on src/components/ui/modals/ModalProvider.tsx
> +  isFullscreen: boolean;
update, this prop name is changing, so we don't need to argue about this!

2024-05-22 13:20 UTC, adamgall approved these changes

2024-05-22 13:29 UTC, merged