`Reskin` | top nav
decentdao/fractal-interface pull request #1838
Opened 2024-05-20 17:57 UTC by DarksightKellar

Wait on review/merged until https://github.com/decentdao/fractal-interface/pull/1834 is finished

Closes #1802 

The updates apply to mobile only, so on desktop, the top nav search behaves the same as always, except with update search result UI:
<img width="920" alt="Screenshot 2024-05-20 at 18 49 38" src="https://github.com/decentdao/fractal-interface/assets/7101382/7bef24be-6179-401f-86d9-a16b891fc53d">

- if already on DAO (existing functionality -- nothing's changed here)
<img width="1302" alt="Screenshot 2024-05-20 at 18 49 58" src="https://github.com/decentdao/fractal-interface/assets/7101382/e39adde2-6838-4079-9fae-ce00e47845e0">

Top nav on mobile:
<img width="412" alt="Screenshot 2024-05-20 at 18 55 05" src="https://github.com/decentdao/fractal-interface/assets/7101382/2d9d69ee-1dae-4164-8ac4-a17da282ed97">

tap search icon:
<img width="417" alt="Screenshot 2024-05-20 at 18 55 18" src="https://github.com/decentdao/fractal-interface/assets/7101382/72e8cf01-55a7-45ed-adb2-881563eccd13">

tap favorites icon:
<img width="391" alt="Screenshot 2024-05-20 at 18 55 36" src="https://github.com/decentdao/fractal-interface/assets/7101382/c5e7674c-34c9-4c02-ac64-6377b04f688e">

2024-05-21 04:34 UTC, Da-Colon approved these changes
Good follow up, Code looks good.

I do think maybe adding a little margin between the SafeRow (the results)? @decentdao/design

2024-05-21 16:29 UTC, nicolaus-sherrill requested changes
Alrightyyyy, there's a lot of changes to be done here. The mobile nav bar is a bit more than a squished desktop nav. We don't have a mobile component built yet but the designs in the handoff file have the updated layout. The primary changes are smaller icons, reduced spacing, a hamburger menu, and a smaller nav height. 

I've outlined the primary changes here:
<img width="849" alt="Screenshot 2024-05-21 at 11 27 56 AM" src="https://github.com/decentdao/fractal-interface/assets/62394931/d06a91eb-8f1d-4310-84d7-3a436466c4c3">

2024-05-21 20:25 UTC, tomstuart123 commented
@DarksightKellar agree with the above. If tight for time, my take is prioritise the smaller icons and hamburger menu on mobile

Let us know if any issue with getting this in pre production push (10.30amest tomorrow).

2024-05-22 13:43 UTC, adamgall approved these changes

2024-05-22 14:00 UTC, merged